- README.md
- backend/README.md
- backend/package.json
- frontend/README.md
CMS-356
This adds README files to the root directory and the frontend and backend dev container directories, which are the three workspaces you'd open up for this project. The three files link back and forth between each other (hopefully).
I set the project up piece-by-piece but it would be very helpful to hear from you about anything that might be missing or unclear in the documentation for someone who has just cloned the repo. 🙏  Let me know!
> CMS-356: Add README files

- backend/index.js
- backend/routes/nested-path-example/orm.js
- frontend/src/config/keycloak.js
- frontend/src/router/ProtectedRoute.jsx
- frontend/src/router/index.jsx
- frontend/src/router/layouts/MainLayout.jsx
- frontend/src/router/pages/Foo.jsx
CMS-321
Expanding on #9 , this changes the page-specific and section-specific auth to protect the entire frontend app, and all the endpoints on the backend (except`/` and the `/time` testing endpoint in the root).
On the frontend, there's no explicit log in/out buttons. If you're not logged in, it will forward you to Keycloak instead of showing anything.
On the backend, it will continue rejecting requests with `401` if you don't send a valid token.
> CMS-321: Protect entire routes with Keycloak

- frontend-legacy/src/components/page/home/Home.js
CMS-416
Now that the new app is running alongside the old Staff Portal sections on the same domain, we noticed that logging out of the old portal won't log you out of the new one. (The new one uses SessionStorage and the old one uses cookies and possibly LocalStorage). This branch is a quick fix to clear SessionStorage on the home page when you're logged out. 
A more comprehensive solution would be to make both sections use the same auth provider, and share the same storage location and tokens. TBD, but this might be worth doing to avoid possible hassles down the road.
> CMS-416: Clear session storage on log out

- frontend/package-lock.json
- frontend/package.json
- frontend/src/global.scss
- frontend/src/main.jsx
- frontend/src/router/index.jsx
- frontend/src/router/layouts/LandingPageTabs.jsx
- frontend/src/router/layouts/LandingPageTabs.scss
- frontend/src/router/pages/EditAndReview.jsx
- frontend/src/router/pages/ExportPage.jsx
- frontend/src/router/pages/PageDetails.jsx
- frontend/src/router/pages/PublishPage.jsx
CMS-425
This branch builds out the elements for the "Publish" and "Export" pages. I moved them in the router config so they're children of the "/" landing page route (and they'll share a tabbed navigation with the "Dates management" table page).
I also removed the table row hover styles from all tables. It's not in the wireframes and I don't want to suggest the row is clickable when it's not.
The layout still uses the built-in Bootstrap container class, even though the wireframes are full width for large screens. I'll discuss with design and see what the final decision is for the responsive layout in another ticket.
> CMS-425: Add Publish and Export pages

- .env.example
- docker-compose.dev.yml
- frontend/.npmrc
- frontend/Dockerfile.dev
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/NavBack.jsx
- frontend/src/main.jsx
- frontend/src/router/pages/EditAndReview.jsx
- frontend/src/router/pages/ExportPage.jsx
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/vite.config.js
- helm/deployment/templates/frontend/frontend-deployment.yaml
- helm/deployment/templates/secrets/adminjs-secret.yaml
- helm/deployment/templates/secrets/fontawesome-secret.yaml
CMS-438
This branch implements a Fontawesome "Pro Kit" instead of the free icon packs we were manually importing. The kit includes all* of the icons we'll need for the project.
Except: *It doesn't include the custom icons, because adding them to the kit would be more trouble than it's worth. I discussed it with the Drive BC devs who had the same experience. It's no trouble to leave the custom icons separate and use an `<img>` tag for those. 
*Note* that this adds a new environment variable to the backend dev container, and hopefully fixes the secrets templates in the Helm charts. You'll need to rebuild your backend dev container.
> CMS-438: Use Fontawesome pro kit

- backend/package-lock.json
- backend/package.json
- backend/routes/api/parks.js
- backend/routes/api/seasons.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/DateRange.jsx
- frontend/src/components/DateRange.scss
- frontend/src/components/EditAndReviewTable.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/components/ParkDetailsSeasonDates.jsx
- frontend/src/components/ParkDetailsSubArea.jsx
- frontend/src/components/StatusBadge.jsx
- frontend/src/hooks/useApi.js
- frontend/src/hooks/useDate.js
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/ParkDetails.scss
- frontend/src/router/pages/ReviewChanges.scss
CMS-452
This branch builds out components for the Park Details page, and hooks it up to data from the API.
I added a useDate hook to let us parse and format dates. We can add other date functions in there as needed.
(I thought about automatically parsing all dates inside the API hook, but that may not be necessary for this MVP)
It also adds a StatusBadge component and replaces the placeholder content on the "Edit and Review" table landing page. It has a hardcoded list of possible status strings.
> Global variable for reviewer 
I think this sill need to be done after we import data from Strapi (or elsewhere). Let me know if there's anything I should do in the meantime.
> Displayed on expansion of accordion 
> - Summary of dates 
> - Notes  
Do we have an endpoint that provides this data …
> CMS-452: Build Park Details components

- frontend/src/components/DateRange.scss
- frontend/src/global.scss
CMS-468
A small change to update the link/text hover color and make it align with the `surface.color.primary.hover` value from the design tokens page. The bootstrap theme had it using a very bright blue that looked out of place.
I also got a warning about Sass syntax so I re-ordered some lines in DateRange.scss while I was at it. It's an unrelated change but I was fixing small style issues in this branch anyway...
> CMS-468: Override theme link hover color

- backend/routes/api/parks.js
- backend/routes/api/seasons.js
- frontend/src/components/EditAndReviewTable.jsx
- frontend/src/components/NotReadyFlag.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/SubmitDates.jsx
CMS-453
- `/seasons` endpoint now returns `readyToPublish` field.
- `/parks` endpoint only returns parks with subAreas that have dates
- status is changed to "requested" after user saves any change. 
- Added not-ready flag component to seasons in which `readyToPublish` is false.
- fixed text for mark approved button
- fixed bug in which `readToPublish` was not being properly set.
> CMS-453: Update status change logic and add not-ready flag

- frontend/src/hooks/useValidation.js
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitDates.scss
CMS-322
This branch adds validation functions for the "SubmitDates" page ("notes" field and the date ranges). The logic turned out to be complicated to implement, even if the rules themselves aren't too bad. 
In our meetings last week, we decided it would be unnecessary hassle to reformat the data into a format to work with React Hook Form, and then write our own custom validators for the data structure (which is dynamic, and deeply-nested). The result is that this whole thing is custom-made, which makes it potentially fragile and error prone! But the benefit is that we can have our data structured the way we want, and run validations without needing to change it and then change it back.
I struggled with the state hooks, updating asynchronously when a field is changed, and then instantly …
> CMS-322: Add form validation hook

- backend/package.json
- backend/routes/api/seasons.js
- backend/strapi-sync/oneTimeDataImport.js
- backend/strapi-sync/sync.js
- backend/strapi-sync/syncData.js
CMS-580
Followed the steps described in the ticket to test.
`syncData()` can run as many times as you want
`oneTimeDataImport()` should only run one time. 
Note that campgrounds are not created here given that the names of the subareas in Strapi are not consistent enough to assign campsite groupings to campgrounds. 
I created a separate script to help with the process, but it will probably need to be verified manually.
> CMS-580: Fix bug that prevents sync script to get all the data.

- frontend/src/components/ChangeLogs.jsx
- frontend/src/components/ChangeLogsList.jsx
- frontend/src/components/ChangeLogsList.scss
- frontend/src/components/ParkDetailsSeasonDates.jsx
- frontend/src/components/ParkDetailsSeasonDates.scss
- frontend/src/router/pages/ParkDetails.scss
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewChanges.scss
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitDates.scss
CMS-591
We had to add the change log notes to the details page, in the expansion panels. I turned the notes list into a component and popped it in there, and made some minor style tweaks to make it match the latest Figma styles.
> CMS-591: Add ChangeLogs (notes) component to details page

- backend/routes/api/parks.js
- frontend/src/components/ConfirmationDialog.jsx
- frontend/src/components/ConfirmationDialog.scss
- frontend/src/components/FlashMessage.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/hooks/useConfirmation.js
- frontend/src/hooks/useFlashMessage.js
- frontend/src/hooks/useNavigationGuard.js
- frontend/src/lib/utils.js
- frontend/src/router/pages/ExportPage.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PublishPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
CMS-517
Both modal windows and flash messages have their own hook. You can use their how to show the element on screen and pass params. It's basically just a way to avoid duplication and send different prop values to the components on demand. 
I also created a hook for the components in which we need to warn the user when they leave the page with unsaved changes. 
- navigating away by clicking a button or a link will show the custom dialog 
- browser-level actions like closing the tab or refreshing would only show the default browser warning
You can check in the ticket where are flash messages and modals supposed to appear. 
The only one that is not included in this PR, because it relates to submitting for review, and that's not part of this version is:
> Submit with missing dates? When …
> CMS-517: add modal windows and flash messages

- backend/strapi-sync/sync.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/TooltipWrapper.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitDates.scss
CMS-590
Some new tooltip text was revealed in a sharepoint doc, which has specific text for certain feature types. I updated the text and made a method to resolve the tooltips for Operating Dates with those feature types.
The new text was very long so I installed react-bootstrap to use their tooltip component because our existing one didn't wrap long lines. Turns out we already had react-bootstrap installed but weren't using it anywhere(?) Good to know! There's probably more stuff in there we can pull in to make our lives easier.
I made a "TooltipWrapper" component so we can use react-bootstrap tooltips anywhere. Mostly copied and pasted the example from their docs.
> CMS-590: Use react-bootstrap tooltip, update content

- frontend/package-lock.json
- frontend/package.json
- frontend/src/hooks/useValidation.js
- frontend/src/lib/utils.js
- frontend/src/router/pages/SubmitDates.jsx
CMS-603
We will basically use UTC everywhere. This is how they are stored in the DB and how they come back from the API. We're making sure that we when format them, the UTC date is displayed and it's not being converted to PST time.
> CMS-603: Fix dates timezone issue. Use UTC dates regardless of timezone.

- backend/package.json
- backend/strapi-sync/create-multiple-item-campgrounds.js
- backend/strapi-sync/create-single-item-campgrounds.js
- backend/strapi-sync/sync.js
CMS-583
Please refer to the ticket to see the logic behind the grouping. 
There are 2 scripts that create campgrounds and assign features to them.
1. For campgrounds that only have one feature, the campground will keep the name of the single feature and the feature will be renamed to "All Sites". This can be optionally displayed on the FE. 
2. For campgrounds that have multiple features, the campground will have it's own general name, and features will have their name that only reflects their specific part of the campground (e.g. "Alice Lake Campground Sites 1-20" -- > "Sites 1-20").
> CMS-583: create campgrounds

- backend/eslint.config.mjs
- backend/index.js
- backend/migrations/20241218185747-add-mgmt-area-jsonb.js
- backend/models/park.js
- backend/package-lock.json
- backend/package.json
- backend/routes/api/export.js
- backend/routes/api/parks.js
- backend/routes/api/seasons.js
- backend/strapi-sync/sync.js
- frontend/src/components/FlashMessage.scss
- frontend/src/router/pages/ExportPage.jsx
- frontend/src/styles/breakpoints.scss
CMS-348
The CSVs require some info we weren't pulling from strapi, and we don't need that info anywhere else so I didn't want to two new FK tables and a junction table just for that. I tried a few approaches and this was the cleanest/simplest one:
- Added a jsonb field to the Park model called "managementAreas" which stores an array like this:
```json
[
{
"mgmtArea": {
"strapiId": 123,
"name": "North Okanagan"
},
"section": {
"strapiId": 57,
"name": "Okanagan"
}
}
]
```
The details get fetched in the normal syncData script, and the CSV export just prints out the names from that array.
In particular, I'd like someone to look at the Sequelize query in the Export endpoint, because was guessing at some of the sub-query/join stuff. I've been testing it since I imported the real Strapi data and …
> CMS-348: Add CSV export feature

- backend/routes/api/seasons.js
- backend/strapi-sync/sync.js
CMS-566
This changes the one-time-data-import script so that seasons and dates will only be created for active features. Some inactive features have missing dates or dates that are also inactive. 
Given that the API considers which features are active and which features have dates, we don't want to create "seasons" for features that wouldn't be returned by the API anyway. 
Note that this requires the database to be recreated and all the syncing process to be done from scratch. Just follow steps 1 to 7 in the readme. 
The `required: false`  in the query is to make the query a left outer join instead of an inner join. This was causing 500 errors given that in some cases dateable was being returned as `null` even though the feature had a dateable.
> CMS-566: fix issue in which some seasons didn't have any dates at all

- backend/routes/api/seasons.js
- frontend/src/router/pages/SubmitDates.jsx
CMS-593
The requirements say that the way to remove an empty date range is to save it or leave the page and come back, and the empty range(s) will be gone.
This branch adds a filter on the frontend and backend to skip saving date ranges where the start and end date are both null. 
It's explicitly checking for two nulls, but we can easily change it to reject if either of them is null. Validation should catch that on the front end, and I don't know if they'll ever want to save a half-done range as part of a draft in the future.
> CMS-593: Skip saving blank date ranges

- frontend/src/components/ChangeLogsList.jsx
- frontend/src/lib/utils.js
CMS-591
Updated the notes/changelog timestamps to match the updates in Figma. Removed the "formatTimestamp" function since it's no longer used. Easy to add back if we need it later.
> CMS-591: Update changelog datestamp

- backend/routes/api/parks.js
- backend/routes/api/seasons.js
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/router/pages/EditAndReview.jsx
- frontend/src/router/pages/SubmitDates.jsx
CMS-598
Updated the text for the "under review" status to "pending review". I don't think we need a migration or anything because there shouldn't be any "under review" values in the db currently, and nothing should ever come from Strapi with that status.
I noticed the status badge component on the frontend doesn't even have a case for "under review"/"pending review" but we can add that in a future release when the status is used.
Right now the only place you'd notice this change is in the filter box for the list of parks on the homepage.
> CMS-598: Update "Pending review" label

- frontend/src/components/ChangeLogsList.jsx
- frontend/src/lib/utils.js
CMS-603
Every date and timestamp is saved in UTC. When displaying date in change logs, we need to uses `America/Vancouver` timezone when formatting to display the accurate day.
> CMS-603: Convert timestamp in change logs to local time when formatting.

- frontend/src/router/pages/SubmitDates.jsx
CMS-595
This fixes a few issues reported by QA with the DatePicker component in the date ranges on the "Submit Dates" page:
1. Disable selection of dates outside of the Operating Year when clicking the calendar
2. If a DatePicker is blank (if you add a new date range, or delete the value) it will open to January of the Operating Year, instead of the current month/year.
3. Allow typing or pasting inputs in a variety of formats before parsing (It waits until you press Enter after typing). I added a bit of a hack to prevent parsing "YYYY-MM-DD" format in the wrong timezone. 
Right now, it should all work the way you'd expect when typing into a date picker box, except if you use the "YYYY-MM-DD" format, the calendar will highlight the previous day because of the timezone offset. It will …
> CMS-595: Update DatePicker configuration

- backend/package-lock.json
- frontend/package-lock.json
- frontend/src/styles/global.scss
- frontend/vite.config.js
CMS-608
Ran npm update and npm audit fix on the backend and frontend to resolve some security advisories. Most of them are coming from the `frontend-legacy` directory, and I've created a task to do something similar on the main repo (and then we can copy the package.json changes into frontend-legacy).
I did a minor change to the SCSS imports to suppress a new warning about "@import" being deprecated.
I didn't do any major updates, so everything _should_ work the same as before. Let me know if anything doesn't.
> CMS-608: Update NPM packages

- frontend/src/hooks/useNavigationGuard.js
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/PreviewChanges.jsx
CMS-618
Instead of staying on the Preview page when you approve dates, now it redirects to the Park Details page.
Most of the changes here were to move the flash message to the Park Details page. I used an "approved" query param and useEffect. I'm not sure I used the hook efficiently so let me know if you think of any improvements.
An improvement for a future version could be to make the flash message global in the layout so we can call it and still change routes.
> CMS-618: Redirect to Park Details on approval

- backend/routes/api/seasons.js
- frontend/src/components/ChangeLogsList.jsx
CMS-613
Excluding SeasonChangeLogs with no notes. It sounds like they might still want these in the future, so I'm just excluding them from the query results here. We're already doing this in the CSV export, so I copied the query part from that.
If you think it's a good idea, we can look into not creating these blank notes at all... and maybe we don't need the DateChangeLogs either?
> CMS-613: Filter empty notes out of /seasons payload

- frontend/src/router/pages/PreviewChanges.jsx
CMS-614
Hides the reservations row in the table on the Preview page, if the feature's `hasReservations` is false. 
Same pattern that's used on the SubmitDates page. 
Note that the Park Details page currently does it slightly differently and doesn't look at hasReservations, but the row is hidden because the "Reservation" date type doesn't exist in the object there. Let me know if you think we should update that too.
> CMS-614: Hide reservations row when hasReservations is false

- frontend/src/lib/utils.js
- frontend/src/router/pages/SubmitDates.jsx
CMS-595
The default behavior of the react-datepicker parses dates and handles interaction events pretty well, but it wasn't working because the page was re-rendering every time a date changed. This adds a "localDateRanges" value for each date range, and only updates the `data` object when you hit enter or blur the input.
I removed the `onKeyDown` handler because the component more or less does this by itself now.
Along with that, some other changes to make that possible:
- Tweaks to allow "null" dates if you clear the input
- `normalizeToLocalDate` - the opposite of `normalizeToUTCDate`
- Swapped the positions of the parameters for `onChange` to be consistent with the new `onDateChange` handler
> CMS-595: Parse date input on blur

- backend/routes/api/export.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/hooks/useApi.js
- frontend/src/router/pages/ExportPage.jsx
CMS-622 (Implements small changes)
CMS-348 (Also fixes regressions that broke this one)
We were just navigating straight to an API endpoint to get the CSV, and I forgot that the auth token check would break that.
This branch implements some small changes to the CSV export page:
- Don't pre-select all feature types
- Add "Select all/none" buttons
- Add selection for the date type: Operating, Reservation, Winter
...and it also changes how the PDF is requested:
- The API returns the CSV text, but without the "attachment" disposition header or the filename
- Filename is constructed on the frontend
- The frontend receives the data and downloads it as a blob with the computed filename
To allow that, I tweaked the API hook's `fetchData` method to return the response data so you don't have to …
> CMS-622: Update CSV export options and functions

- frontend-legacy/src/components/page/advisorySummary/AdvisorySummary.js
CMS-530
- Remove 'www' from the links copied from the advisory summary page
- `const url` logic is no longer needed since we migrated all data to Strapi
> CMS-530: Remove 'www' from the links copied from the advisory summary page

- backend/routes/api/export.js
- backend/strapi-sync/sync.js
CMS-622
A quick fix to update the display name for the DateTypes on the CSV page (and in the CSV file). 
In the future, we can update the values in the DB but for now let's just translate the values on the frontend until the values are finalized.
I updated the name for "Winter fees" in the sync script; rather than re-running it, I'm just going to update the value in AdminJS on Alpha-Dev/Alpha-Test/etc.
> CMS-622: Use display names for date types on Export page

- backend/import-all-data.sh
- backend/index.js
- backend/migrations/20250130212845-add-has-winter-fees-dates-field.js
- backend/models/feature.js
- backend/routes/api/winter-seasons.js
- backend/strapi-sync/sync.js
CMS-467
- added endpoint to get winter season details
- added sh script to run all commands needed to restart your db and import all the data
- added boolean field `hasWinterFeeDates` to `Feature`
- import winter dates from strapi during the `one-time-data-import` command.
> CMS-467: Add endpoint to get winter season and import winter dates

- backend/routes/api/seasons.js
- backend/routes/api/winter-seasons.js
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-673
Added the "save" endpoint for winter dates, and the related frontend stuff (flash messages, confirmations, and save functions).
53fbb21 pretty much copies the code from the normal season endpoint, and then I discovered we can use `bulkCreate` with `updateOnDuplicate` to potentially cut down on the number of INSERT/UPDATE queries by a lot, so a35a0c3 updates the endpoint code to use that. Check it out and let me know what you think!
> CMS-673: Add "save winter dates" endpoint

- backend/routes/api/winter-seasons.js
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
CMS-676
Copied the regular season Preview page and tweaked a few spots to suit the Winter fee dates. 
I added the "hasReservations" and previous season reservation dates to the API payload for this page too.
b8225d9 is just a copy of the regular preview page, and 3a2bb02 has some sections changed for the Winter fee data, if you're curious about the differences between the two pages.
> CMS-676: Add Preview page for Winter fee dates

- backend/routes/api/export.js
- backend/routes/api/seasons.js
- frontend/src/components/ParkDetailsSeasonDates.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/SubmitDates.jsx
CMS-635
Backend changes
- the backend returns "" (empty string) for features that have "all sites" as their name for regular seasons (winter seasons are unaffected because they have different logic for the name)
- for export endpoint, use same logic as winter seasons to display "campground name: feature name" or just campground name when feature name is "All sites".
Frontend changes:
- for regular seasons, hide feature name when is empty string.
> CMS-635: Adjust feature name 'All sites' to display proper name.

- frontend/src/styles/global.scss
CMS-670
Some global style rules to address display issues from QA. On pages with long headers, such as "Anhluut'ukwsim Lax̱mihl Angwinga'asanskwhl Nisg̱a'a Park [a.k.a. Nisg̱a'a Memorial Lava Bed Park] 2025 season dates" it will wrap on whitespace as usual when possible, and then wrap inside long words as a last resort, so long words like "Angwinga'asanskwhl" won't overflow the container and break the layout.
QA also requested making the horizontal padding on the page container 16px (1rem) so I tweaked that here too by increasing the gutter-x bootstrap variable from 1.5rem to 2rem. (It gets divided in half for each side)
> CMS-670: Update global styles: header wrap and horizontal padding

- frontend/src/components/ReadyToPublishBox.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewChanges.scss
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitDates.scss
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.scss
CMS-671
Style updates for the "Back/Save/Preview" buttons on all pages: On smaller screens, they display vertically stacked, full width. On wider screens, they show side-by-side like before. This is all done with Bootstrap classes, so I took out the custom CSS for it.
I also fixed some classes in the "Ready to publish" box above it, so that will be spaced correctly too.
> CMS-671: Update "Save" control spacing on all pages

- frontend/src/contexts/AccessContext.js
- frontend/src/hooks/useAccess.js
- frontend/src/router/AccessProvider.jsx
- frontend/src/router/ProtectedRoute.jsx
CMS-658
There was a linter warning saying "quick refresh" only works if a jsx file exports nothing but a single component. I split the access context for user roles from router/AccessContext into contexts/AccessContext and router/AccessProvider
The context is usable from the useAccess hook, but that's not being used yet in this release anyway.
> CMS-658: Split up access context and provider

- frontend/src/styles/global.scss
CMS-639
Some overrides to the bootstrap theme to make disabled buttons resemble the BC Gov design system
(Greyed out instead of faded out, no border, and the cursor changes to a 🚫)
> CMS-639: Update styles for disabled buttons

- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/components/ParkDetailsSeasonDates.jsx
- frontend/src/router/pages/ParkDetails.scss
- frontend/src/router/pages/SubmitDates.jsx
CMS-623
Minor updates to the Park details page to order the date types so Operating dates are always listed first, plus some layout and style changes.
This branch also includes a minor fix to the `key` on the Edit page, to fix a console error when two date ranges have the same dates. It came up while I was fixing the date order so I included it here.
> CMS-623: Update date order, park page

- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitDates.scss
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/styles/_datepicker.scss
- frontend/src/styles/global.scss
CMS-624
Overriding some styles in the DatePicker component to show the Month/Year dropdown in place of the Month/Year header text. (Normally they'd both show, which looks kinda awkward)
> CMS-624: Show month dropdown instead of header

- backend/routes/api/seasons.js
- frontend/src/components/ConfirmationDialog.jsx
- frontend/src/components/ConfirmationDialog.scss
- frontend/src/components/MissingDatesConfirmationDialog.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/hooks/useConfirmation.js
- frontend/src/hooks/useMissingDatesConfirmation.js
- frontend/src/hooks/useNavigationGuard.js
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/PublishPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-517
- changing button labels specific to each modal
- changing some titles that were updated in the wireframes
- navigate to park details page when user saves draft
- create new confirmation dialog with text input that will be added to the notes
Copied from my comment on https://bcparksdigital.atlassian.net/browse/CMS-517
- The modal for “Edit public dates on API?” appears twice on the wireframes with different titles “Edit published dates?“. But according to this ticket, the title should be “Edit public dates on API?“.
- I don’t know if there’s a difference between the “Exit without saving?” modal and the “Discard changes?“ modal. Some notes on this.
- Navigating away by clicking the back button next to “save draft“ or by clicking the BC parks logo would show the “Discard changes?“ …
> CMS-517: Update modal button labels and fix modal workflow issues

- backend/migrations/20250219192557-change-season-updatedAt.js
- backend/models/season.js
- frontend/src/components/ParkDetailsSeason.jsx
CMS-706
- updatedAt timestamp on Season will be null on creation because we want to show that a season has "never" been updated on the DOOT. 
- added a migration to allow null values on that field 
- added a hook on the Season model that sets the value to null on creation
> CMS-706: updatedAt timestamp on Season will be null on creation

- backend/strapi-sync/sync.js
CMS-717
- Changed the sync script so that it ignores the `hasReservations` flag from Strapi until it has been cleaned up.
- Changed date creation to use `bulkcreate` instead of multiple DB queries.
- Features with reservation dates will be updated to have `hasReservations: true` in a single DB query
- Features with winter feee dates will be updated to have `hasWinterFeeDates: true` in a single DB query.
> CMS-717: Update sync script to properly set hasReservations

- backend/middleware/adminJs.js
CMS-721
From the ticket comments:
Updating the sync script to make all 2025 dates “empty” can have other implications and it would mean that none of the 2025 season dates would be imported from Strapi. So, any important dates that were already created for that season would be missing in the DOOT and there wouldn’t be a way to import them unless we created a separate script. Additionally, if updated the sync script that would remove that from all environments even if it’s useful for QA or devs in other environments. 
So, instead of updating the script I added an action button to the seasons in the Admin.js dashboard that lets you clear the data for a group of seasons. That way, you can choose to clear the data for:
an individual season you want to test
all the seasons for a given park and …
> CMS-721: Allow users to clear dates data from a group of seasons.

- frontend/src/router/pages/ExportPage.jsx
- frontend/src/styles/global.scss
CMS-639
A small fix for the disabled styles on one button on the Export page. I switched it to use the "disabled" attribute instead of the CSS class. But then I also updated the styles to apply to the class anyway.
> CMS-639: Use disabled attribute instead of class

- backend/strapi-sync/sync.js
CMS-732
Incorrect flag name on sync script prevented winter fee features from being fetched.
> CMS-732: Correct hasWinterFeeDates flag name on sync script

- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewChanges.scss
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-467
Minor changes from the design review feedback for winter fees:
- Tweaked the column widths on the preview page date tables. Now they'll tend to look a bit better on very big or very small screens
- Updated both Edit pages and both Preview pages to include the "Ready to publish" toggle when calculating the "hasChanges" logic. If you flip the switch but don't make any other edits, it will now count as a "change" and let you click save.
> CMS-467: Update winter fees frontend pages

- backend/routes/api/seasons.js
- backend/routes/api/winter-seasons.js
CMS-467
Manually sorting the features array in JS, because I couldn't get the sequelize "order" to work here (?)
Using Elk Lake Park as an example, frontcountry campgrounds with more than one feature were sometimes listed out of order. This will fix them for winter and non-winter seasons, on the Park details page and the edit and preview pages since they all use the same endpoints.
> CMS-467: Sort features in API endpoints

- frontend/src/router/pages/PublishPage.jsx
CMS-740
A quick fix for a duplicate key console error. I added the season to make the key more specific to the table row.
> CMS-740: Fix feature-year row key

- frontend/src/router/pages/PaginationBar.jsx
CMS-719
A small fix to hide the "Previous / Next" buttons on the main page when your other filters have no results. Previously, the buttons still showed with no page numbers, and the "Next" button was clickable.
> CMS-719: Hide pagination for empty results

- frontend/src/components/FeatureIcon.jsx
- frontend/src/components/ParkDetailsFeatureType.jsx
CMS-739
Updated the PropTypes for the `FeatureIcon` component to make the `icon` prop optional. It will show a default icon for feature types with a "null" icon (such as "Trail")
> CMS-739: Update PropTypes for optional icons

- frontend/src/components/FlashMessage.jsx
- frontend/src/components/FlashMessage.scss
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/hooks/useValidation.js
- frontend/src/router/pages/ExportPage.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/PublishPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-650
This adds flash messages for incidental errors caused by calls to `fetchData` or `sendData`. In most of these places, we were just using console.error to print the error and there was no indication to the user. I left the console lines in, but added a red flash message.
I also left room for a third kind of flash message to alert the user when validation fails. (To be discussed with UX)
> CMS-650: Add error flash messages

- backend/import-all-data.sh
- backend/package.json
- backend/strapi-sync/create-missing-dates-and-seasons.js
- frontend/src/components/DateRange.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/lib/utils.js
CMS-735
- Added a script to create missing dates and seasons for 2025, this ensure that users can add dates for 2025 for every feature. Basically, the script will go through every feature:
- check that a corresponding 2025 season exists for that feature, if it doesn't exist, create it
- create an operation date for that feature-season if there's none
- create  a reservation date for that feature-season if there's none and that feature allows for reservations
- same process for winter fee seasons
- when there's a previous dateRange that has null values for `startDate` or `endDate`, "Not submitted" will be displayed consistent with the wireframes. 
- fixed small bug in which "not available" was displayed side by side with no spacing instead of different lines.
See the ticket for screenshots …
> CMS-735: Add missing dates and seasons

- frontend/src/components/EditAndReviewTable.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/router/index.jsx
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/router/paths.js
CMS-437
I couldn't find a way to resolve routes by a name or ID in React, so I've added a "paths" file with functions that take park/season IDs and return the URL paths.
This branch replaces all the hard-coded URL paths in all of the links and `navigate` calls, and uses the resolvers instead.
I also updated the non-winter season URL paths to be consistent with the winter-fees, and made the resource names plural.
```
park/:parkId/edit/:seasonId
park/:parkId/edit/:seasonId/preview
park/:parkId/winter-fees/:seasonId/edit
park/:parkId/winter-fees/:seasonId/preview
```
```
parks/:parkId/seasons/:seasonId/edit
parks/:parkId/seasons/:seasonId/preview
parks/:parkId/winter-fees/:seasonId/edit
parks/:parkId/winter-fees/:seasonId/preview
```
> CMS-437: Update URL paths, use resolvers

- frontend/src/components/ConfirmationDialog.scss
- frontend/src/components/MissingDatesConfirmationDialog.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/router/pages/ExportPage.jsx
- frontend/src/router/pages/PreviewChanges.jsx
CMS-517 and CMS-743
Mostly changing labels and some other info displayed on modals.
For CMS-517: 
- For export:
- ‘Check your downloads for the Excel document.’ < lowercase ‘downloads’ request from Rob
- For ‘Edit public dates on API?’
- Updated button to ‘Continue to edit’ < the team would prefer the longer version of this
For CMS-743, it's all about the confirmation dialog when approving a season with missing dates: 
- Incorrect button labels displayed as “Cancel” and “ Confirm”
- Missing the word count for the text field
- Missing the date type information along with the subarea details in the bullet point. 
- Should show the Subarea name and the date type
- Missing the required field indication
> CMS-517: Update labels and info notes on modal windows.

- backend/import-all-data.sh
- backend/middleware/adminJs.js
- backend/package.json
- backend/routes/api/publish.js
- backend/strapi-sync/create-missing-dates-and-seasons.js
- backend/strapi-sync/create-multiple-item-campgrounds.js
- backend/strapi-sync/create-single-item-campgrounds.js
- backend/strapi-sync/import-data.js
- backend/strapi-sync/oneTimeDataImport.js
- backend/strapi-sync/reset-and-import-data.js
- backend/strapi-sync/sync.js
- backend/strapi-sync/syncData.js
CMS-657
- added ability to run the sync script from the admin dashboard. However, instead of recreating the DB, it will just delete all the contents and re-run the sync script to import the data
- past seasons will default to "on API" instead of requested
- sync script will use the STRAPI_URL environment variable. This is needed so that we can test the publish workflow.
- every time we import something and publish it to Strapi we'll publish to the equivalent environment. 
- For this to work, we need the featureId (PKs and FKs) to match what's on the environment. 
- this means the STRAPI_URL environment variable will be needed in each env and it will need to match the CMS API URL for that environment. `https://alpha-dev-cms.bcparks.ca, https://alpha-test-cms.bcparks.ca, …
> CMS-657: run sync script from dashboard

- backend/migrations/20250304210219-add-cascade-delete-to-datechangelogs.js
- backend/models/daterange.js
- backend/routes/api/seasons.js
- frontend/src/components/ReadyToPublishBox.jsx
- frontend/src/lib/utils.js
- frontend/src/router/layouts/LandingPageTabs.jsx
- frontend/src/router/layouts/LandingPageTabs.scss
- frontend/src/router/layouts/MainLayout.jsx
- frontend/src/router/pages/EditAndReview.jsx
- frontend/src/router/pages/Error.jsx
- frontend/src/router/pages/ExportPage.jsx
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/ParkDetails.scss
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewChanges.scss
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/PublishPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitDates.scss
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.scss
- frontend/src/styles/global.scss
CMS-631
Big ticket with lots of changes on the Submit and Preview pages for winter and regular seasons. I should have split it into several branches 🙈 And I could still do that if it's too ridiculous to review. Here's a summary:
There are screenshots in the ticket to clarify this stuff:
- Update the `NavBack` component text and link target to match what's currently in Figma
- Update validation styles: always show the icon, and always show red text on a white bg.
- Update spacing and header level for h1, h2, h3, h4's
- Update the header for regular seasons to match the new style already used on the Winter pages
- Remove fancy spacing for previous dates and just show plain text ("Previous: Fri, Mar 15...")
- Improve positioning of the dash between the date range inputs
Use a CSS …
> CMS-631: Update Edit/Preview pages

- backend/middleware/adminJs.js
CMS-723
Some fixes to the configuration for the db session manager used by AdminJS. I copied from their quickstart tutorial at the time, but it wasn't actually working.
1. Change "username" to "user" in the session db connection config. Previously it was defaulting to "node" and failing silently 😬 And just storing the session in memory
2. Rename the table so it's less ambiguous, and capitalized for consistency with the other tables. You might need to manually drop the existing `session` table or reset your DB so it can create constraints with the same name.
3. Other small config tweaks: reduced the cookie length from default 1 day to only 10 hours. That's the same as the Keycloak session length. You can stay logged in all day, but it will log you out overnight.
Now that your session …
> CMS-723: Fix session cookie/store

- frontend/src/hooks/useValidation.js
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-757
Validation will not be run when user clicks "save as draft". So users will be able to save dates with only field populated or clear both fields and those changes will be reflected in the DB. 
This applies only when saving as draft. When clicking "continue to preview" the validation wouldn't prevent that.
Apparently we need to start validating as soon as dates are entered. But that is captured in another ticket, so this ticket doesn't deal with it. 
https://bcparksdigital.atlassian.net/browse/CMS-756
Since requirements have been changing and they were never explicitly captured for saving data -- refer to https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Saving+and+submitting+dates
> CMS-757: Allow users to save incomplete dates as draft

- frontend/src/hooks/useValidation.js
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/styles/global.scss
CMS-756
Previously, we waited until the form was submitted before running validation, and we only showed one error at a time.
Now, we check all validation at all times, and show all the errors at once. Except the "Enter a start/end date" messages, which are bypassed until you try to submit the form.
To accomplish this:
- Run `validateForm` on every input in a `useEffect` (and use `useCallback` with all of the related functions so it works). I moved the other functions outside of the `useValidation` hook to keep them separate.
- Got rid of the specific `onUpdateDateRange` callback because `validateForm` runs on every change now.
- Instead of returning on the first error, check everything and keep track of the overall valid state with a boolean. Pass it up to `validateForm` so it can return …
> CMS-756: Update validation: always check the whole form

- backend/routes/api/seasons.js
- backend/routes/api/winter-seasons.js
CMS-760
A small tweak to order the dates by the start date in the API. I posted an example in the ticket, but basically If you have these dates: 
if you change "Jan 8" to "Jan 1", I'd expect that date to be listed first when you save dates and reload the page. Only when you re-fetch the data, and doesn't sort any of the dates you change on the fly.
A small change in the season endpoints should affect anywhere dates are listed in the frontend. The CSV export is already sorted like this (sorted by feature, then startDate)
> CMS-760: Order date ranges by start date

- backend/routes/api/seasons.js
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
CMS-799
I just noticed this recently: the preview pages weren't including the `deletedDateRangeIds` in the payload, so the query broke trying to get IDs from `undefined`. This ticket updates the frontend to always send arrays, and also makes the parameter optional in the backend.
> CMS-799: Fix saving from preview page

- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-763
Another quick fix for a more visible bug: this fixes some unwanted text wrapping at certain screen sizes (~1060px wide) when the loading spinner shows next to the submit buttons.
I moved the buttons outside of the 6-column container, since they don't need to have their width constrained.
> CMS-763: Move submit buttons outside of row container

- frontend/src/components/ContactBox.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitDates.scss
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.scss
CMS-631
Some minor tweaks to the spacing and ordering in the date range rows on the Submit pages:
- Messages are generally closer to the input boxes.
- The "Remove this row" button will show underneath any error messages on small screens when everything is vertical.
Also increased the spacing between the notes and the "Ready to publish?" sections.
> CMS-631: Update date row spacing/ordering

- backend/middleware/permissions.js
- backend/routes/api/publish.js
- backend/routes/api/seasons.js
CMS-588
Added backend permission checks based on https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Roles?
The only checks missing are the ones based on bundles mapping users to specific parks. But there is another ticket in the backlog for that.
> CMS-588: backend role checks

- backend/strapi-sync/create-missing-dates-and-seasons.js
- backend/strapi-sync/park-winter-dates.js
- backend/strapi-sync/sync.js
CMS-779
The logic for creating winter seasons is different than regular seasons. This ticket will update how winter seasons are created.
Past winter seasons
Winter fee dates apply only to certain parks, so winter seasons are created only when all the following conditions are met:
The feature (subarea) belongs to one of the parks in this list (refer to the [spreadsheet](https://docs.google.com/spreadsheets/d/13k7wJjgaJBSiOreyyQQTIZxc_DCNZ1bD/edit?gid=646395629#gid=646395629)).
The feature type is Frontcountry campground.
The feature's operation dates overlap with the park-wide winter fee dates for that year.
When these conditions are met, a winter fee season is created for all applicable features in each qualifying year. For each season, we try to include any existing offSeasonDates from …
> CMS-779: Update logic of how winter dates are created

- helm/crunchy-postgres/values-prod.yaml
No specific ticket
Increased the sizs of the volume claim for crunchyDB backups, and also bumped up the number of DB replicas and retained backups on prod.
I applied the chart already, but I'll keep this as a draft for a bit in case tweaks are needed.
> CMS-000: Update prod helm chart for crunchy db

- frontend/src/components/ReadyToPublishBox.jsx
CMS-633
A small change to add a flag icon to the text in the "Ready to publish" section of the Edit/Preview pages
> CMS-633: Add flag icon to "Ready to publish" text

- frontend/src/components/ParkDetailsFeatureType.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/hooks/useConfirmation.js
- frontend/src/hooks/useNavigationGuard.js
- frontend/src/router/index.jsx
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/SeasonPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/router/pages/WinterFeesSeasonPage.jsx
- frontend/src/router/paths.js
CMS-577
A pretty huge branch. The main goal here is to add the "Review" page, but it involved a lot of fundamental changes to the editing and approval flow:
- Display and work with the live data edited in the browser, instead of just reading the saved data from the API
- Re-think how and where the data is validated
- The button on the Park details page for approvers now says Review and goes to the new Review page (instead of Preview). 
- The Review page re-uses the Preview page component with a prop `review=true` that simply changes some heading text, and the buttons at the bottom. Otherwise it's the same as the Preview page.
I refactored the Edit and Preview pages (for normal and winter seasons) to be sub routes of a "Season" page component. They share a lot of logic, so that's being …
> CMS-577: Refactor Edit/Preview, add Review page

- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/SeasonPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
CMS-625
Added the ability to specify an anchor ID in `navigateAndScroll` to go to that anchor instead of the top of the page. Clicking the "edit" links for a specific feature and date on the Preview page will take you to that section of the Edit page.
The entire page re-renders and the child component states are all reset whenever the data changes 😭 so I couldn't think of a cleaner way to do this and had to resort to using a setTimeout. I hope we can improve this in the future.
> CMS-625: Scroll to sections on edit page

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/PaginationBar.jsx
- frontend/src/components/ParkDetailsSeasonDates.jsx
- frontend/src/hooks/useValidation.js
- frontend/src/router/pages/EditAndReview.jsx
- frontend/src/router/pages/SeasonPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/router/pages/WinterFeesSeasonPage.jsx
CMS-655
Swapped out the 686KB `lodash` package for the tree-shakable `lodash-es`. Now it's only 123KB in the bundle, accounting for just 6.68% of the total app size, where it was 28.1% before.
I also simplified the imports, because now they can be tree-shaken. Importing submodules makes no difference to the bundle size.
> CMS-655: Replace lodash with lodash-es, simplify imports

- helm/README.md
- helm/crunchy-postgres/README.md
- helm/crunchy-postgres/values-training.yaml
- helm/deployment/values-training.yaml
CMS-482
Adding a new environment to the `test` namespace for training RSOs and POs. This is kind of a mix of the `test` and `alpha-test` environments:
- Same deployment specs as `alpha-test` - 1 DB replica, no cloud backups, same RAM/CPU
- Pulls from the `alpha-test` Strapi API - Still confirming that this is correct
- Builds from the `test` tag so it will deploy the same image as the one used for UAT
> CMS-482: Add helm charts for training environment

- frontend/src/hooks/useNavigationGuard.js
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/SeasonPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/router/pages/WinterFeesSeasonPage.jsx
CMS-759
This is a small change to turn the `hasChanges` function into a `useMemo` hook. I didn't think of it when I initially wrote that code. 😅  Hopefully it will cut down on unnecessary re-renders, or at least make the code a bit more maintainable. 
It's the same changes in the regular seasons and the winter seasons.
> CMS-759: Memoize hasChanges

- backend/routes/api/seasons.js
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/components/StatusBadge.jsx
- frontend/src/config/permissions.js
- frontend/src/hooks/useNavigationGuard.js
- frontend/src/router/layouts/LandingPageTabs.jsx
- frontend/src/router/pages/ParkDetails.jsx
- frontend/src/router/pages/PreviewChanges.jsx
- frontend/src/router/pages/PreviewWinterFeesChanges.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-637
This branch adds the "DOOT Submitter" user role. If a user has a "doot-submitter" role (and not a "doot-approver" or "doot-super-admin") they will see a few different elements in the UI:
- Removed buttons and wording for "Review" 
- Removed the "Approve" button and added a "Submit for approval" button
- Added a backend endpoint for the button above, which changes the season's status to "pending review" - mostly copied from the "approve" endpoint.
- On the frontend, we had a method to "save and approve" and we needed to add "save and submit" so I refactored them both to use "save and POST" and share most of their code.
Instead of specifically checking if the user is a submitter, the logic actually checks if the user _is not an approver_. There will be roles for RSOs and POs in the …
> CMS-637: Add submitter role, "Pending review" state

- frontend/src/components/DateRange.jsx
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/components/ParkDetailsSeasonDates.jsx
- frontend/src/components/ParkDetailsWinterFeesDates.jsx
- frontend/src/hooks/useApi.js
- frontend/src/hooks/useValidation.js
- frontend/src/lib/utils.js
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-606
We currently convert between date strings and date objects in several places when dates are stored or manipulated. This branch transforms all dates to date objects when the data is loaded (in the Axios instance) and then the dates are objects for the whole lifecycle of the app until they're sent back to the API. This will reduce complexity where we had to convert formats (and in some cases, time zones).
The changes involve mostly removing places where ISO date strings are parsed, and overall it simplifies things a bit. 
A future change we could make would be to store the date ranges as DATEONLY types in the db, so they wouldn't have the hour part and suffer from time-zone complications. But that can happen later on if we decide it will be helpful.
> CMS-606: Transform date strings in useApi

- backend/strapi-sync/new-structure-migration.js
- backend/strapi-sync/sync.js
CMS-753
- Migrate `adminNote` from `park-operation-sub-area-date` to `dateRange`
- In `dateRange`, `adminNote` wasn't migrated so that needed to update sync.js and re-import Strapi data
- Remove `attributes` from `park-operation-sub-area` data and `park-operation-sub-area-date` data in sync.js
- ^ No longer nested structure in `park-operation-sub-area` and `park-operation-sub-area-date` since this change https://github.com/bcgov/bcparks.ca/pull/1598
- Migrate all `dateRange` data to `park-feature-date`
- In park-feature-date 2641, in date ranges 3010, according to Diego, it's because we won’t import any date that is inactive or that belongs to an inactive subare
> CMS-753: Migrate date range to park-feature-dates collection

- frontend-legacy/src/components/composite/responsiveDrawer/responsiveDrawer.js
- frontend-legacy/src/components/page/appDashboard/AppDashboard.css
- frontend-legacy/src/components/page/appDashboard/AppDashboard.js
- frontend/src/components/NavSidebar.jsx
- frontend/src/components/NavSidebar.scss
- frontend/src/components/TouchMenu.jsx
- frontend/src/components/TouchMenu.scss
- frontend/src/router/layouts/MainLayout.jsx
- frontend/src/router/layouts/MainLayout.scss
CMS-634
This branch adds a navigation sidebar, and a mobile touch menu to navigate between the different sections of the Staff Portal. I also added a DOOT link to the legacy staff portal's nav menus. Internal links use React router/MUI tabs etc. but external links between the two portals just use a plain `a` tag with `href`.
**Note** that the links won't work in local dev because the legacy portal and DOOT dev servers run on different ports. But on alpha-dev etc they use the same hostname.
I used bootstrap styles and tweaked it a bit to _resemble_ the old menu. I wasn't trying to get it to match exactly because the "v2" section of the Staff Portal (DOOT) doesn't use Material UI. The sizes and colors in the old menus aren't all in the design tokens, but I tried to get it "close enough" …
> CMS-634: Add portal nav menus

- frontend/src/components/TouchMenu.jsx
- frontend/src/router/layouts/MainLayout.jsx
CMS-634
A quick fix for the header menus ticket to fix the breakpoints where the menus show/hide.
The touch menu button was hiding at the `md`/medium breakpoint, but the side menu wouldn't show until the `lg`/large breakpoint, so there was a gap in between where no menus would be accessible. This fixes it so the touch menu shows until the `lg` breakpoint. (`md` felt a bit too cramped with the sidebar next to the dense table on the homepage)
> CMS-634: Fix menu breakpoints

- backend/import-all-data.sh
- backend/index.js
- backend/middleware/adminJs.js
- backend/migrations/20250509221029-add-dateable-to-all-levels.js
- backend/migrations/20250510004215-add-publishables.js
- backend/migrations/20250510014335-add-season-type.js
- backend/migrations/20250510052223-update-old-seasons.js
- backend/models/feature.js
- backend/models/featuretype.js
- backend/models/index.js
- backend/models/park.js
- backend/models/parkarea.js
- backend/models/publishable.js
- backend/models/season.js
- backend/package.json
- backend/routes/api/parks.js
- backend/routes/api/publish.js
- backend/routes/api/seasons.js
- backend/routes/api/winter-seasons.js
- backend/strapi-sync/create-missing-dates-and-seasons.js
- backend/strapi-sync/import-data.js
- backend/strapi-sync/re-sync-data.js
- backend/strapi-sync/reset-and-import-data.js
- frontend/src/router/pages/ParkDetails.jsx
CMS-853
This is a big update that does a few things:
1. Adds a `dateable` column to the ParkAreas and FeatureTypes table (it's already on Park and Feature) so we can add dates at any level. We probably won't need to add dates for FeatureType in this version, but the system will be flexible enough to support it if we need to. `dateable` associates **DateRanges** with Park/ParkArea/FeatureType/Feature
2. Adds a `publishable` junction table, similar to the `dateable` junction table, but separate so we can edit/publish a "Season" independently from what other levels or features are inside it. `publishable` associates **Seasons** with Park/ParkArea/FeatureType/Feature
3. Updated the error handler in the backend server so it will actually print the error message instead of just the stack. 
4. …
> CMS-853: Add "publishable" to the data model

- helm/crunchy-postgres/templates/PostgresCluster.yaml
No ticket
We had to make this change to the Crunchy DB deployment helm charts yesterday after something changed on the server and everyone's deployments stopped working. Some details from the chat:
> A quick update to the `spec.openshift: true` issue! according to the docs, if the `spec.openshift` flag isn't set, the operator is supposed to detect the environment automatically. It seems that the operator is normally able to detect this correctly and so nobody really needed to set it before. However, there was a problem with the openshift API last night and my current guess is that this caused the operator to fail to detect the correct environment when restarting your containers. This would explain why the fix is a config change despite the fact that nobody changed anything that would …
> CMS-000: Specify openshift: true in PGO spec

- backend/README.md
- backend/package.json
- backend/tasks/create-seasons.js
CMS-465
Added a `npm run create-seasons <operating year>` script to create new records in the Seasons table to request dates for new operating years.
The script basically takes a year as input and then loops over all of the relevant Parks/ParkAreas/Features it finds and creates a new Season for it.
I updated the documentation to include instructions, but let me know if you have questions!
> CMS-465: Add create-seasons script

- frontend/src/router/layouts/MainLayout.jsx
CMS-932
When you first log into DOOT, the template makes a request to get your User info (to display your name in the header). It only does that once, and the template stays the same as you navigate between pages. 
There's a middleware to get your user details from the JWT token on every API request, and it adds you to the Users table if you're not there already:
```js
/* middleware/users.js */
// Find or create user in the database
const [user] = await User.findOrCreate({
attributes: ["id", "email", "name"],
where: { email },
defaults: { name },
});
```
Currently, a page will render the template _and_ the contents at the same time. If you're a new user, it will be requesting the user details and the page contents at the same time. These two (or more) requests might all try to create new …
> CMS-932: Hide contents until userData is loaded

- backend/middleware/adminJs.js
- backend/routes/api/parks.js
- frontend/src/components/EditAndReviewTable.jsx
- frontend/src/components/EditAndReviewTable.scss
- frontend/src/components/FormPanel.jsx
- frontend/src/components/FormPanel.scss
- frontend/src/components/PublishTable.jsx
- frontend/src/components/StatusBadge.scss
- frontend/src/router/pages/EditAndReview.jsx
- frontend/src/styles/global.scss
CMS-894
- BE: Display `operatingYear` in the Season on AdminJS (not related to this ticket)
- BE: Modify the `/park` endpoint
- Add `parkArea`
- Get `dateRange` by `deatableId` and group the dates by `dateType`
- Get the custom date range group in `park`, `parkArea` and `feature` - use it as `groupedDateRanges`
- Get `feature` by `parkAreaId` in `parkArea`
- Get `featureType` in `parkArea` if `parkArea.features` have the same `featureType`
- Get `season` by `publishableId` in `parkArea` and `feature`
- Get `season` by `feaureType.publishableId` in `parkArea` and `feature`
- Filter `season` by `operatingYear` - no need to get data if it's before last year
- FE: Update the dates management table
- Display Park, Park Area, and Feature level information
- Remove the Park Details page 
- …
> CMS-894: Update dates management table

- backend/routes/api/export.js
CMS-792
- Looks like it returned the Unix epoch time if a date parameter is empty, so change it to return an empty string
> CMS-792: Check if a date is empty

- backend/constants/seasonStatus.js
- backend/middleware/adminJs.js
- backend/migrations/20250611210638-change-on-api-to-published.js
- backend/routes/api/publish.js
- backend/routes/api/seasons.js
- backend/strapi-sync/create-missing-dates-and-seasons.js
- backend/strapi-sync/sync.js
- backend/tasks/create-seasons.js
- frontend/src/components/ParkDetailsSeason.jsx
- frontend/src/components/StatusBadge.jsx
- frontend/src/hooks/useValidation.js
- frontend/src/router/pages/EditAndReview.jsx
- frontend/src/router/pages/SeasonPage.jsx
- frontend/src/router/pages/SubmitDates.jsx
- frontend/src/router/pages/SubmitWinterFeesDates.jsx
- frontend/src/router/pages/WinterFeesSeasonPage.jsx
CMS-895
A few small changes in this branch:
- Update the text displayed to the user for various season statuses
- Change the value in the db from "on API" to "published" to make it more clear
- Changed the db value for "Not provided" to "not provided" so they'll all be uniformly lowercase. 
- Add a constants file with the db values for every season status, so we don't have to memorize "magic strings" in the backend code.
> CMS-895: Update status wording

- backend/migrations/20250611230755-add-park-winter-col.js
- backend/models/feature.js
- backend/models/park.js
- backend/routes/api/publish.js
- backend/strapi-sync/create-missing-dates-and-seasons.js
- backend/strapi-sync/sync.js
- backend/tasks/populate-park-tier-types/populate-park-tier-types.js
- backend/tasks/populate-park-winter-fee-flag/2025-winter-parks.json
- backend/tasks/populate-park-winter-fee-flag/README.md
- backend/tasks/populate-park-winter-fee-flag/populate-park-winter-fee-flag.js
CMS-969
This ticket removes the `hasWinterFeeDates` field from the Feature model and puts it in the Park model.
I added a one-time script to populate the columns using the same parks list we already had from the client. The `hasWinterFeeDates` field is not used by anything at the moment but it will be used by the Season edit form, and the scripts to publish approved dates / create requested dates when we eventually implement them.
> CMS-969: Move hasWinterFeeDates to Park level

- frontend/src/components/FormPanel.jsx
CMS-896
- Allow clicking outside of the form panel to close it
- Note: Not urgent but it'd be good to come back here again to discuss whether we should display an alert/warning before closing it to avoid unintentional behaviour
> CMS-896: Allow clicking outside of form panel to close it

- frontend/src/components/ConfirmationDialog.scss
- frontend/src/components/FormPanel.jsx
- frontend/src/hooks/useConfirmation.js
- frontend/src/hooks/useMissingDatesConfirmation.js
- frontend/src/hooks/useNavigationGuard.js
- frontend/src/router/pages/EditAndReview.jsx
- frontend/src/router/pages/PublishPage.jsx
CMS-929
Similar to the flash message changes in #228 , I renamed and removed some stuff with the existing modal window code to make it easier to use, and added it in some of the approve/save/close functions for the Edit form.
I moved the "save" payload stuff into a memoized variable, and used that to check if the form has any unsaved changes.
I also simplified the navigationGuard hook and re-implemented that now in the form component to prevent closing the tab when you have unsaved changes.
> CMS-929: Add modal windows and navigation guard

- helm/deployment/values-training.yaml
CMS-1044
Update the training environment to use the prod BCeID & Keycloak.
As part of this change, I also had to add an entry to "Valid redirect URIs" for the `staff-portal` client on Keycloak prod. 
This was the new entry `https://training-staff.bcparks.ca/*`
> CMS-1044: Use prod Keycloak for training environment

- frontend/src/components/DatePicker.jsx
- frontend/src/components/DateRangeFields.jsx
- frontend/src/styles/_datepicker.scss
CMS-996
This fixes the bug that caused the tab to freeze and crash when opening the month dropdown, now that we moved the datepicker to the Offcanvas panel. I implemented the fix you found on the library's github page, so thank you for finding that!
I also added another commit to move the component into its own file. I refactored it a bit and made a DatePicker component that wraps the third party one. I called it `<DootDatePicker>` on the page to avoid confusion.
> CMS-996: Fix crash when opening month dropdown

- frontend/src/components/FormPanel.jsx
CMS-929
Noticed a bug with my original branch - the "Move back to draft?" modal was coming up all the time because I had the wrong check. It should only come up if the season is already approved/submitted/requested. This branch is a quick fix for that.
> CMS-929: Fix "Move back to draft?" prompt check

- backend/utils/propagateWinterFeeDates.js
CMS-898
I noticed a bug with the process that propagates Winter fee dates from the Park down to the Features/Areas:
If you approve the Park-level season last (and the Park season is the season that triggers this function), the `getSeasonPark` function returns the Season instead of the Park, then the check for `hasWinterFeeDates` will always be false and it will return without doing anything.
This branch is a quick fix for that. The other season types should work either way.
> CMS-898: Fix return value for getSeasonPark

- backend/tasks/create-date-range-annual/README.md
- backend/tasks/create-gate-details/README.md
- backend/tasks/create-seasons.js
- backend/tasks/populate-date-ranges/README.md
- backend/tasks/populate-date-ranges/populate-date-ranges.js
- backend/tasks/populate-park-gate-dates/README.md
CMS-1043
- Create this PR to try a different approach for CMS-1043, based on our conversation in https://github.com/bcgov/bcparks-staff-portal/pull/236
- Populate date ranges based on the previous year's dates if `isDateRangeAnnual` is TRUE
- Case 1: Populate dates when Seasons are newly created 
- e.g. Run `create-season 2026`
- If the date type has `isDateRangeAnnual` is TRUE, 2026 dates will be populated based on 2025 dates
- Case 2: Populate dates when the current Seasons do not have dates
- e.g. Run `populate-date-ranges 2025`
- If the date type has `isDateRangeAnnual` is TRUE and no DateRange of the year, 2025 dates will be populated based on 2024 dates
> CMS-1043: Populate date ranges if dates are the same every year

- backend/routes/api/seasons.js
CMS-1070
The Area Season form won't show any area-level dates. Every Area has at least one feature (even if it's a fake feature we created called "All sites"). I thought we'd use the area-level to create dates that applied to all the features, but it sounds like we're not doing that at the moment.
The area-level form will still show feature dates, and the gate hours will be the only area-level thing on it. Let me know if my changes will cause problems with the gates section, but I think it won't affect it!
> CMS-1070: Omit Area-level dates from Area form

- backend/routes/api/parks.js
- backend/routes/api/seasons.js
CMS-898
After discussing this feature with UX and QA today, we realized it's not needed until later on, and the logic may change. Amanda asked to simply disable it for now, and hide Winter fees at the feature/area level on the homepage, and we'll revisit it in a future sprint.
(We're not collecting winter fees at those levels, they'd be generated by the `propagateWinterFeeDates` script which is being commented out here, but the temporary `filter` lines will hide any that exist in the DB for any other reason)
> CMS-898: Temporarily disable winter fee propagation to features

- frontend/src/components/SeasonForms/ParkSeasonForm.jsx
CMS-1087
The data is currently incomplete, so many Parks in the BCParks Reservation System have the `inReservationSystem` value false. As a workaround until the data is updated, we've tweaked the logic in the Parks form:
If inReservationSystem is false, then fall back and check the Tier 1, Tier 2, and Winter dates columns. If any of them are true, then consider `inReservationSystem` to be true as well.
If all of them are false, that means there will be no date types to collect besides the Gate Operating dates at the Park level, so the top section of the form won't show anyway. Some of the other checks we added today are now going to be redundant... but at least it will support it if we ever add more date types at the Park level. 
More stuff we can refactor in the future 🫠
> CMS-1087: Fall back to checking T1/T2/Winter if BCP Res. check is false

- backend/middleware/checkJwt.js
CMS-1106
This branch makes some changes to the JWT token checking middleware we're using. It was fine for months and then it started occasionally throwing false 401 errors with no indication of why. And when these 401 errors happened, it would continue along the middleware chain (and still save data, even though it was responding with a 401)
- Wrap the JWT middleware to handle errors and print them out so we can debug if anything weird happens
- The wrapper will also make sure to cancel the middleware chain if there's an error by passing any errors to the global error handler in index.js
- Increase the JWKS Requests Per Minute to 10. I don't think this is the cause of the problem, but it could help 🤷
> CMS-1106: Fix intermittent false 401 errors

- frontend/src/components/EditAndReviewTable.jsx
- frontend/src/contexts/RefreshTableContext.js
- frontend/src/router/pages/EditAndReview.jsx
CMS-1014
This hooks up the "Approve" button on the homepage table. It does the same thing as if you opened the form and clicked "Mark approved" in there:
- Update the status to "Approved"
- Reload the data in the table to show the changes
- Show a success flash message
I added yet another context to provide the main table's refreshTable function down to the ApproveButton, rather than passing it down 5 or 6 levels. 
I also renamed the "renderTable" functional component to ParksTableWrapper and used a proper tag for it in the JSX. I think that was left over from v1 when it was some of the first React code I ever wrote 🙈 
This branch is pretty quick and basic; I put in a TODO comment about handling API errors and I'll be sure to add something to the backlog for that. I also had the idea to …
> CMS-1014: Implement approve button on table rows

- backend/migrations/20250724232555-add-backcountry-permits-feature-col.js
- backend/models/feature.js
- backend/routes/api/seasons.js
- backend/strapi-sync/sync.js
- backend/tasks/create-seasons.js
- backend/tasks/populate-date-ranges/README.md
- backend/tasks/populate-date-ranges/populate-annual-date-ranges.js
- backend/tasks/populate-date-ranges/populate-blank-date-ranges.js
- backend/utils/dateTypesHelpers.js
CMS-970
A bunch of related changes in this ticket:
1. created a "dateTypeHelpers" file and moved some shared/repeated code in there: get all dateTypes, and get the ordered list of dateTypes for the given Park/Feature
2. Added `hasBackcountryPermits` to the Feature model to conditionally show the Backcountry registration date type.
3. Updated the sync script to pull in the hasBackcountryPermits value
4. renamed populate-date-ranges to populate-**annual**-date-ranges
5. Created a new script to go with it called populate-**blank**-date-ranges and updated the Readme file in that folder
6. updated `create-seasons` to call both scripts in order
This script finds all of the seasons for the given operatingYear (so they have to exist already, from create-seasons) and then looks at all of the …
> CMS-970: Bulk create blank dates

- .gitignore
- backend/middleware/users.js
- backend/migrations/20250729210202-add-username-col.js
- backend/migrations/20250730001613-add-username-to-useraccessgroups.js
- backend/migrations/20250730002814-remove-email-constraints-from-useraccessgroups.js
- backend/migrations/20250730004622-add-username-constraints.js
- backend/models/accessgroup.js
- backend/models/user.js
- backend/models/useraccessgroup.js
- backend/tasks/populate-access-groups/README.md
- backend/tasks/populate-access-groups/agreement-example.json
- backend/tasks/populate-access-groups/populate-access-groups.js
CMS-1045
This ticket phases out the "email" field for users (which is not reliable or stable) and adds a "username" field, which is stable, but impossible to know until the user is in keycloak 🙃 
1. add the username column to the Users table - it can't be null, so the migration also adds a string like `TEMPORARY_asdfsd` for existing users. But you can delete unused users before you run the migration too. Otherwise you'll have to update the users with their keycloak usernames.
2. add the username column to UserAccessGroups
3. remove email column constraints from UserAccessGroups
4. add username FK constraints to UserAccessGroups and remove email column
- Updated the User, AcessGroup, and UserAccessGroup models to match the db changes.
Updated the usersMiddleware to use the username: If a …
> CMS-1045: Use username instead of email for AccessGroups

- frontend/src/components/DateRangeFields.jsx
- frontend/src/components/GateForm.jsx
- frontend/src/components/SeasonForms/AreaSeasonForm.jsx
- frontend/src/components/SeasonForms/FeatureSeasonForm.jsx
- frontend/src/components/SeasonForms/ParkSeasonForm.jsx
- frontend/src/lib/isDateTypeOptional.js
- frontend/src/styles/global.scss
CMS-1082
Added a new function to return true if a date type is "optional" at the given level. If it's optional, we show a label under the date type header. 
Also added some logic to hide and disable the "X" button to remove dates:
- If a date is not optional, you won't be able to remove them all; there must always be one left.
- If a date is optional, you can still remove them all.
- Instead of removing the button entirely, I made it disabled and invisible so the flex box elements stay the same size. We can update this with a CSS grid later on...
Added a CSS class for the "secondary' color, which is very close to black. Some things in Figma are colored in this dark grey shade so we can use this class for that. The "secondary" color in the Bootstrap is blue 🙃 so I called it …
> CMS-1082: Add "Optional" labels, disable "X" for single dates

- backend/tasks/populate-access-groups/populate-access-groups.js
CMS-324
A small update for the AccessGroups changes from CMS-324, this just makes the default behavior to clear the database tables every time. I don't think there's any drawback to doing this every time. The benefit is, if anybody is removed from an AccessGroup, this will update that without us having to manually delete the record.
> CMS-324: Always reset AccessGroups tables when populating new bundles

- backend/tasks/populate-date-ranges/populate-blank-date-ranges.js
CMS-970
A quick fix to the script that populates blank date ranges - it was returning early when there were no dates to create, so sometimes the "create blank gate operating dates" section would never be reached. Now it will continue through the process, even if there are 0 dates to create, so the second script will always be called.
> CMS-970: Remove early return before creating blank gate dates

- backend/routes/api/parks.js
- backend/tasks/create-seasons.js
CMS-1020
- When next year's seasons are created (e.g. 2026), the year after the next seasons will be created for the group campsites (e.g. 2027), but these seasons weren't displayed in the table and the form because the season used `feature.publishableId`, not `parkArea.publishableId`
- Updated `create-season` script to create seasons for the group campsites based on `parkArea.publishableId` if its `feature` belongs to `parkArea`
- If not, create seasons based on `feature.publishableId`
- Updated the `/park` endpoint to display empty date ranges as "Not provided" for the last year's season in the table
- For testing, run `node tasks/re-sync-seasons-and-dates/re-sync-season-and-dates.js`
> CMS-1020: Use park area publishable id for group camping feature seasons

- backend/routes/api/parks.js
- frontend/src/router/pages/EditAndReview.jsx
CMS-1097
- Some gate data on PROD is incorrect and needs to be reviewed by the content team, but given the UAT date is coming, I added a workaround to the park filter
- There is a case where a park has the Operating dates but no gate. 
- The park filter by date type "Operating (Gate)" should filter based on `hasGate`, not `dateType` "Operating"
> CMS-1097: Filter parks by hasGate

- frontend/src/hooks/useValidation/rules/completeDateRanges.js
- frontend/src/hooks/useValidation/useValidation.js
CMS-510
The requirements for the basic validation ticket have changed, so I implemented this rule that was not applicable before 👍 
Now, any dateRange with a start date but no end date will show "Enter an end date" when you try to submit.
And likewise, if you have an end date but no start date, you'll see "Enter a start date"
> CMS-510: Add "completeDateRanges" validation rule

- backend/tasks/populate-date-ranges/populate-blank-gate-dates.js
CMS-970
Another fix to the script that creates blank Operating gate dates:
- The query wasn't using the transaction because it wasn't passed correctly
- The query wasn't properly filtering the seasons and date types.
This commit should fix both of those issues.
I already copied the file up to the alpha-test environment and ran it there, and it seemed to work 🙈
> CMS-970: Fix season/dateRange filter in create-blank-gate-dates

- frontend/src/components/FormPanel.jsx
- frontend/src/hooks/useValidation/useValidation.js
CMS-1176
A small change to allow "Save Draft" even if there are validation errors. I added a second parameter to the onSave function to "allow invalid" and now I'm returning the errors as an array, and then throwing an exception if there's anything in the array.
I think we will need this later on if Approvers need the ability to bypass validation errors for unusual park rules.
Approving and Submitting are still not allowed but Saving drafts will be allowed with errors. 
I'll mention in the ticket, the error where you have to provide a note if you're editing previously approved/published dates can be bypassed now... but we can add an exception or something for that in another ticket. This ticket is just to allow saving with errors.
> CMS-1176: Allow save draft if there are validation errors

- frontend/src/components/SeasonForms/AreaSeasonForm.jsx
CMS-1185
- Add a `dateableId` filter to previous dates at the feature in the park area level
> CMS-1185: Add a filter to previous dates at feature in park area level

- backend/migrations/20250818235750-add-in-reservation-system-field-to-parkarea.js
- backend/models/parkarea.js
- backend/routes/api/parks.js
- backend/tasks/populate-in-reservation-system/README.md
- backend/tasks/populate-in-reservation-system/populate-in-reservation-system.js
- frontend/src/components/FilterPanel.jsx
- frontend/src/router/pages/EditAndReview.jsx
CMS-947
- Added a new field `inReservationSystem` to `ParkArea`
- Created a script to populate `inReservationSystem` at the `ParkArea` level from `inReservationSystem` at the `Feature` level 
- ^ For testing, run `node tasks/populate-in-reservation-system/populate-in-reservation-system.js`
- Updated the filter text to "BCP reservations only"
- Updated the filter logic
- `Park` level dates only appear if they contain Tier 1, Tier 2, or Winter fee dates
- `ParkArea` level dates appear if they are `inReservationSystem`
- `Feature` level dates appear if they are `inReservationSystem`
> CMS-947: Update filter for bcp reservations

- backend/routes/api/seasons.js
- frontend/src/components/DateRangeFields.jsx
- frontend/src/components/SeasonForms/FeatureSeasonForm.jsx
- frontend/src/hooks/useValidation/rules/reservationSameAsTier1And2.js
- frontend/src/hooks/useValidation/rules/tier1and2NoOverlap.js
- frontend/src/hooks/useValidation/rules/tier1and2SameAsReservation.js
- frontend/src/hooks/useValidation/useValidation.js
- frontend/src/lib/consolidateDateRanges.js
CMS-1078
Added 3 more validation rule functions. These ones check if the Reservation dates in a Feature/Area form are exactly equal to the combined Tier 1 and 2 dates for the Park, and vice-versa.
I had to add some metadata to the Park and Area API payloads to include the Park Tier1/2 dates, and include the feature reservation dates in the Park payload.
I still need to confirm some of the logic with Amanda but everything else is ready to review as-is. If I have to change anything, I'll explain it in a comment.
> CMS-1078: Add Tier 1 & 2 validation rules

- frontend/src/hooks/useValidation/rules/reservationEndsBeforeOperatingEnds.js
- frontend/src/hooks/useValidation/rules/reservationWithinOperating.js
CMS-1180
A minor update to the validation functions - for the "Operation + Reservation" rules, instead of showing the message at the bottom of the form, we're now showing it under both the Operation dates section and the Reservation dates section. 
See before and after screenshots in the ticket, CMS-1180
The Tier 1 + Tier 2 validation rules already do this, so this ticket just updates the Operation + Reservation rules to use the same pattern. Now nothing is using the "dateableSection" validation message slot, but I'm leaving it in for now, in case we need it for other rules.
> CMS-1180: Show validation errors under Operation/Reservation sections

- frontend/src/components/FormPanel.jsx
- frontend/src/hooks/useValidation/useValidation.js
rename onSave for clarity
CMS-1149
The onSave function was showing the "saved" confirmation flash message every time it got called. This was a problem because the onSubmit and onApprove functions call onSave. 
Approve would open the "saved" flash message and then quickly replace it with the "approved" flash message, so the user wouldn't notice. However, "Submit to HQ" doesn't have its own confirmation flash message yet, so the "saved" message would remain.
This branch changes two things:
1. Move the "saved" flash message into the "prompAndSave" wrapper function, so only "Save draft" clicks will show the flash message.
2. Rename onSave to saveForm. It doesn't get called from clicking any buttons, it only gets called from other functions, so it was slightly confusing to have a name with …
> CMS-1149: Move "saved" flash message to promptAndSave

- frontend/src/components/EditAndReviewTable.jsx
CMS-1015
- Disable the approve button in the park table when the status is Approved/Published/Requested by HQ
> CMS-1015: Disable approve button when not applicable

- backend/tasks/populate-park-tier-types/2025-tier-data.json
- backend/tasks/populate-park-tier-types/populate-park-tier-types.js
CMS-1215
This branch has two small commits, since it was a very quick fix and I had time:
1. Updated the "2025 park tier data" to add Tier 1 dates for Golden Ears. It was the only park that had Tier 2 without Tier 1, and we've been asked to request Tier 1 dates for consistency. This will make the Tier 1+2/Reservation date validation work for Golden Ears as well. 
Run `node tasks/populate-park-tier-types/populate-park-tier-types.js` and `node tasks/create-seasons.js 2026` to test it. I'll update the post-deploy tasks list, but this will be handled by the re-sync-all script anyway 👍 
2. An optional second commit to slightly optimize the script: Skip the update query if the column value didn't change, and close the DB connection at the end if the script is called directly. This prevents it …
> CMS-1215: Set hasTier1Dates for Golden Ears Park

- backend/tasks/create-seasons.js
CMS-1194
An extra filter for the features that get seasons requested for "the next year" (ie 2027) - it should only be for features in the BCP reservation system.
This is a 2.0.1 ticket, so I'll move it down in the git history so it can come right after the current v2.0.1-uat.1 tag. It shouldn't cause any conflicts because it just changes the one line in one backend file, but I'll give everyone a heads up before I do that 😛
> CMS-1194: Filter nextYearFeatures for in inReservationSystem

- backend/routes/api/export.js
CMS-1239
A new requirement has emerged for the CSV export feature: now we will include all date ranges in the document, even those with no start or end date.
Testing it on my local db, the CSV has 1180 rows, which exactly matches the number of dateRange records for that year.
```sql
-- to get the number of dateRanges for 2026 in psql, for example
select count(*) from "DateRanges" where "seasonId" IN (SELECT id from "Seasons" where "operatingYear" = 2026);
-- On my local environment, with a freshly-reset DB from the production CMS, the query returns this:
count 
-------
1180
```
Then export a 2026 CSV from the same environment and note the number of rows (including the header row at the top)
> CMS-1239: Include incomplete date ranges in CSV

- backend/routes/api/export.js
CMS-1240
A new requirement has emerged for the CSV export feature: We need to display a feature type for Park Area dates. Park Areas don't have a feature type, but we'll do what we're doing elsewhere, which is to just use the feature type of the first feature in the area.
Now, the CSV will have a value in the "Feature type" column for all dates, except Park-level dates.
It would also be blank if there was a ParkArea with no features, but that case doesn't exist in the data right now.
> CMS-1240: Display first feature type as park area type

- backend/routes/api/export.js
CMS-1242
On the CSV export, the Feature name was missing if the Feature was part of a ParkArea. This branch adds a function to find the name of the Feature that the DateRange relates to:
- If it's a Feature season, return the name of that one Feature
- If it's a ParkArea season, find the feature with the matching Dateable ID and return its name
- If it's a Park, there's no Feature name so just return `""`
> CMS-1242: Fix missing names for Area-Features

- backend/routes/api/export.js
CMS-1249
Updating the logic for the "In BC Parks Reservation system" column in the CSV:
For Park-level dates, that value in the DB is currently incomplete, so we implemented some logic on the frontend to compensate for this. This branch adds that same logic for Park-level dateRanges in the CSV:
If `park.inReservationSystem` is false, then still return true if any of the following are true:
(`park.hasTier1Dates` || `park.hasTier2Dates` || `park.hasWinterFeeDates`)
> CMS-1249: Use special logic to determine Park inReservationSystem value

- backend/routes/api/export.js
CMS-1238
- Filter out rows where `hasGate` is false and `dateType` is "Operating (Gate)"
- Not export gate times or annual status if `hasGate` is false
> CMS-1238: Update gate detail logic

- backend/routes/api/parks.js
NOBUG
- Hide park area if it does not have active features at `/park`, since the park area itself won't have dates
> CMS-000: Hide park area if it does not have active features

- frontend/src/router/pages/EditAndReview.jsx
CMS-1261
This fixes an issue where users with the doot-all-park-access role were still having access group filtering applied to the list of parks.
> CMS-1261: skip bundle check for users with doot-all-park-access

- backend/routes/api/publish.js
- backend/tasks/populate-previous-dates/populate-previous-dates.js
- frontend/src/router/layouts/LandingPageTabs.jsx
- frontend/src/router/pages/PublishPage.jsx
- frontend/src/router/pages/PublishPage.scss
- frontend/src/styles/global.scss
CMS-899
- Add the publish page back for HQ stuff
- Update the API `/ready-to-publish` endpoint using the v2 data model
- Update the publish table and display park, area, features, and year
- Update populatePreviousDates to change 2025 Tier 1& 2 dates season status "approved" to "published" so that there will be no seasons on the publish page
- For testing, run `node tasks/populate-previous-dates/populate-previous-dates.js`
> CMS-899: Add publish page
