bcgov/bcparks-staff-portal

backend/Dockerfile.dev, backend/index.js, backend/routes/home.js, backend/routes/nested-path-example/hello.js, backend/routes/nested-path-example/orm.js, docker-compose.dev.yml, frontend/Dockerfile.dev, frontend/src/router/pages/App.jsx, frontend/vite.config.js
CMS-390
Changed the ports on the dev servers to avoid conflicts with the main BCParks project:
Backend API: **8100**
Frontend React web app: **8101**
Database: **8102** <- this doesn't even _need_ to be forwarded to the host machine, but we may want to connect to it with a Postgres client at some point
=> CMS-390: Change ports on dev

.github/workflows/build-dev.yaml, .github/workflows/deploy-alpha-test.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, .github/workflows/on-tag-push.yaml
None
- Please refer to this PR for bcparks.ca: https://github.com/bcgov/bcparks.ca/pull/1493
=> NOBUG: Add oc tools installer action

frontend/package-lock.json, frontend/package.json, frontend/src/global.scss, frontend/src/main.jsx, frontend/src/router/index.jsx, frontend/src/router/layouts/MainLayout.jsx, frontend/src/router/layouts/MainLayout.scss, frontend/src/router/pages/DatesManagement.jsx
CMS-423
Updated the layout on the "Dates management" landing page. The filter controls and the table are all still non-functional at this point, and haven't been abstracted into React components.
I installed font awesome and did some minor tweaks to the main layout.
=> CMS-423 Build landing page layout

frontend/src/global.scss, frontend/src/router/index.jsx, frontend/src/router/pages/PageDetails.scss, frontend/src/router/pages/SubmitDates.jsx, frontend/src/router/pages/SubmitDates.scss
CMS-426
Built and styled the elements for the "Submit dates" (aka Edit dates) page. Similar to #18 and #17 it's just the html and CSS. We'll hook it up to the API data and make working components in a separate ticket.
- I wrapped the other page(s) style sheets in a selector to limit their scope to the one page ("Hide whitespace" in the PR diff to make it readable).  If there's a more elegant way to scope a stylesheet to one component/page, please let me know! (css modules?)
- An example URL for local testing is http://localhost:8101/v2/park/foo/edit/bar-baz (`/park/<park ID>/edit/<season ID>`)- I'm now thinking we might want to put the `/edit` at the end, but it may not make a difference here. 
- I'm trying to get it to match the wireframes as closely as possible while using built-in …
=> CMS-426: Build layout for Submit dates page

backend/.dockerignore, backend/.env.local.example, backend/.gitignore, backend/db/connection.js, backend/index.js, backend/middleware/adminJs.js, backend/package-lock.json, backend/package.json, helm/deployment/templates/backend/backend-deployment.yaml, helm/deployment/templates/secrets/adminjs-secret.yaml
CMS-409
This branch adds a basic installation of AdminJS, hooked up to our example db models from Sequelize ORM
=> CMS-409: Install AdminJS

frontend/src/router/index.jsx, frontend/src/router/pages/ParkDetails.jsx, frontend/src/router/pages/ParkDetails.scss
CMS-424
Follow-up to #18 - fixing the "PageDetails" name, which should be "ParkDetails" 🙈
=> CMS-424: Fix "Park details" page name

frontend/src/components/NavBack.jsx, frontend/src/components/NavBack.scss, frontend/src/router/index.jsx, frontend/src/router/layouts/MainLayout.jsx, frontend/src/router/pages/ParkDetails.jsx, frontend/src/router/pages/ReviewChanges.jsx, frontend/src/router/pages/ReviewChanges.scss, frontend/src/router/pages/SubmitDates.jsx
CMS-427
The last page of elements/styles to build out (I think). The next step will be to set up the API and then turn these static HTML elements into React components when the API is ready.
=> CMS-427: Build "Preview" page elements

frontend-legacy/src/components/composite/advisoryForm/AdvisoryForm.js, frontend-legacy/src/validators/AdvisoryValidator.js
CMS-372
- Pass link error status to validator
- Copied over from https://github.com/bcgov/bcparks.ca/pull/1511
=> CMS-372: Pass link error status to validator

frontend-legacy/src/components/page/parkAccessStatus/ParkAccessStatus.js
CMS-506
- Remove smoking ban references
- For the details please refer to https://bcparksdigital.atlassian.net/browse/CMS-49
=> CMS-506: Remove smoking ban references

README.md, frontend-legacy/README.md, frontend/README.md, helm/README.md, helm/crunchy-postgres/README.md, helm/tools/README.md, tools/imagetag-prune/README.md
CMS-458
* Some small changes to get the frontend readme file up to date now that there's an extra step with the FontAwesome access token. (I should have done this in the same branch 🙈)
* Tweaked the legacy frontend readme for accuracy now that it's copied into this repo.
* I also updated the helm readme files while I was at it, just so they'll have syntax highlighting when we read them, and I fixed a couple of typos.
=> CMS-458: Update frontend/OCP readmes

frontend-legacy/src/components/composite/header/Header.js
None
- Update staff portal title in header so it's easier to see which SP you visit
=> NOBUG: Update staff portal title in header

frontend/src/styles/global.scss
CMS-468
Added underlines to the hover state for links, link-style buttons, and plain text-style buttons.
=> CMS-468: Add hover underline to link styles

frontend/src/components/ParkDetailsSeasonDates.jsx
CMS-566
Fixed expansion panel bug. Previously was only showing features that belong to campgrounds. Now, it should show every other type of feature as well.
=> CMS-566: Fix expansion panel bug to show all features

frontend/src/components/ParkDetailsSeason.jsx, frontend/src/styles/global.scss
CMS-574
A small fix to address some requirements from QA: Change the "Preview" button to say "Review" and have it always be disabled, since it will never be requiring review in this version.
=> CMS-574: Update Review button and disabled styles

frontend/src/router/pages/SubmitDates.jsx
CMS-594
The "Back" button at the bottom of SubmitDates wasn't hooked up, so I copied the pattern from the PreviewChanges page. It navigates to the park details page, same as the "NavBack" link at the top of the page.
=> CMS-594: Hook up "Back" button on SubmitDates

frontend/src/hooks/useValidation.js, frontend/src/router/pages/SubmitDates.jsx, frontend/src/styles/global.scss
CMS-332
More requirements emerged for the validation ticket, so I've implemented them here:
1. Show a red "*" next to the notes field when it's required (when the dates have been approved or submitted already)
2. Add a ⚠️ icon to the range- and feature-level error messages, and highlight the related fields in red
3. Add the missing calendar icon back to the DatePicker inputs
4. Turn the feature-level error message into a bootstrap alert-style box
=> CMS-332: Update validation UI

frontend/src/lib/utils.js
CMS-592
Added the year to the date formats, only for the "Previous: " date range string.
=> CMS-592: Update date format for "Previous" ranges

frontend/src/components/ContactBox.jsx
CMS-596
Updates the "Contact Box" component to match the latest updates from Figma
=> CMS-596: Update ContactBox copy

frontend/src/components/ReadyToPublishBox.jsx
CMS-597
Updated the "Ready to publish" box component to match the latest updates from Figma
=> CMS-597: Update "Ready to publish?" text

backend/strapi-sync/create-multiple-item-campgrounds.js, backend/strapi-sync/create-single-item-campgrounds.js, backend/strapi-sync/sync.js
CMS-583
Simply changed names and groups to Match Brett's comments in this spreadsheet.
https://docs.google.com/spreadsheets/d/1iiID3CTLhCkWj_xYm18Igqu6kAVJZxvRuU36dJPVWhU/edit?gid=2112563935#gid=2112563935
=> CMS-583: Update campground names and groups based on spreadsheet

frontend/src/router/pages/EditAndReview.jsx, frontend/src/router/pages/PaginationBar.jsx
CMS-599
Added some basic pagination to the table on the home page. It sounds like the number of rows per page will be decided once they've had a chance to test it, but for now I've gone with 20.
=> CMS-599: Add table pagination

frontend/src/router/pages/EditAndReview.jsx
CMS-599
Changed the pagination bar on the main page to be center-aligned, as requested by UX
=> CMS-599: Center-align pagination bar

backend/routes/api/export.js, frontend/src/router/pages/ExportPage.jsx, frontend/src/router/pages/ExportPage.scss
CMS-348
Some minor tweaks to the CSV export
=> CMS-348: Update CSV export form & filename

frontend/src/components/ParkDetailsSeason.jsx
CMS-603
Add timezone for lastUpdated field. 
This keeps the pattern consistent that we use local timezone for timestamps and UTC for any dates inside of the form.
=> CMS-603: Update 'last updated' field to use local timezone.

frontend/src/components/MultiSelect.jsx, frontend/src/router/pages/EditAndReview.jsx
CMS-620
1. Close the status filter box on the homepage when you click outside of it
2. Show the number of selected statuses on the status filter button
=> CMS-620: Update status filter UX

frontend/src/styles/global.scss
CMS-620
Added styles to the Bootstrap dropdown toggle button to make the arrow point upwards when the menu is open.
=> CMS-620: Flip the dropdown icon upside down on open

frontend/src/router/pages/SubmitWinterFeesDates.jsx, frontend/src/router/pages/SubmitWinterFeesDates.scss
CMS-675
This is an update of #95 to use the new data structure in #96
It simplifies things nicely from the other PR for the most part.
> Added a "Submit dates" / "Edit dates" page for Winter fee dates. Very similar to the non-winter seasons, but with a slightly different data structure. I also used a couple of "contexts" to try to make the components more like pure functions. Even if they're still not... The regular season page has them all nested inside the root component, but they're at least separate functions here, thanks to the contexts providing the data to all the children.
> 
> This ticket doesn't include any validation, so I have that commented out for now. The "submit" and "save" functions will also be handled in separate tickets, so they just print the data to the console at …
=> CMS-675: Add "Edit" page for Winter fees

backend/strapi-sync/sync.js, frontend/src/router/pages/PublishPage.jsx
CMS-338
- Fix bug with incorrect import path (the build failed on merging the previous branch)
- Switched back to import data from prod untill we have featureId in every environment in Strapi.
=> CMS-338: Fix bug with incorrect import path.

backend/routes/api/publish.js
CMS-707
Update logic so that winter fee seasons are included in the publish tab.
=> CMS-707: Include winter fee seasons in publish tab

backend/routes/api/publish.js
CMS-720
Fix 500 error in publish tab.
Error happens when a feature has a non-winter-fee seasons approved but NO winter-fee seasons approved.
Just added a check to skip loop that is causing the error.
=> CMS-720: Fix 500 error in publish tab related to winter fees

frontend/src/router/pages/SubmitDates.jsx, frontend/src/router/pages/SubmitWinterFeesDates.jsx
CMS-710
Show not available when previous dates are missing
- Operation dates
- Reservation dates
- winter dates
=> CMS-710: Show 'Not available' when previous dates are missing

backend/middleware/adminJs.js, helm/deployment/templates/backend/backend-deployment.yaml, helm/deployment/values-alpha-dev.yaml, helm/deployment/values-alpha-test.yaml, helm/deployment/values-dev.yaml, helm/deployment/values-test.yaml, helm/deployment/values.yaml
CMS-721
Just switched environment variable so that it's something we can use across environments.
=> CMS-721: Enable admin dev controls based on env variable

backend/strapi-sync/create-multiple-item-campgrounds.js, backend/strapi-sync/create-single-item-campgrounds.js
CMS-724
Temporarily change campgrounds script so that the sync script keeps working (sill pulling data from prod)
=> CMS-724: temporarily readjust campgrounds script

backend/routes/api/seasons.js
CMS-717
Missing date type on `api/seasons/:id` was causing frontend to crash. 
The issue was happening when a feature has `hasReservations: true` but currently not reservation dates available for that season. This is not an inconsistency and can happen often, especially with new seasons. 
The fix is simply to include both date types in the payload. 
This ticket also includes the fix for CMS-733. 
Using `Season.update()` will update the `updatedAt` timestamp
But using `myseason.save()` will not update it.
=> CMS-717: Fix issue where some date types could be missing in the payload

frontend/src/router/pages/EditAndReview.jsx
CMS-660
Slight changes to the status filters for the data table:
- Default selection is nothing
- If nothing is selected, show everything
- If anything is selected, only show what's selected
- (If everything is selected, show everything)
So it's similar to the filters in the sidebar on shopping sites where initially nothing is selected but everything still shows.
=> CMS-660: Update filter selection logic: select none = select all

frontend-legacy/package-lock.json, frontend-legacy/package.json
None
- Fix an issue that the users couldn't log in to the Staff Portal by updating `keycloak-js`
- TODO: SP has a lot of outdated libraries and high vulnerabilities ... need to update them
=> NOBUG: Fix keycloak login issue

backend/routes/api/parks.js
CMS-699
We don't need to fetch dates and features. This endpoint was created when other filters were needed and we didn't have a good idea of the payload size.
=> CMS-699: Optimize parks endpoints by reducing payload

frontend/src/components/MultiSelect.jsx, frontend/src/components/MultiSelect.scss, frontend/src/router/pages/EditAndReview.jsx
CMS-621
Minor tweaks to the "Clear filters" button - position and focus style
=> CMS-621: Update Clear filter button appearance

frontend/src/components/FlashMessage.scss
CMS-630
Small ssatyle changes to the FlashMessage component: vertical position for the close button, and width constraints.
=> CMS-630: Tweak FlashMessage styles

frontend/src/components/EditAndReviewTable.jsx, frontend/src/router/layouts/LandingPageTabs.jsx, frontend/src/router/layouts/LandingPageTabs.scss, frontend/src/styles/global.scss
CMS-629
Small tweaks to the "Edit and review" page. I expect the "border style" change on the table to be required on all pages with tables in the future, so I made it a global style. If we have to do the same on the Publish page table, we can just add that `has-header-row` class.
=> CMS-629: Update Edit and Review page styles

helm/README.md, helm/crunchy-postgres/values-prod.yaml, helm/deployment/templates/backend/backend-deployment.yaml, helm/deployment/values-prod.yaml, helm/deployment/values.yaml
CMS-657
Updates to the helm charts for PROD deployment, etc.
=> CMS-657: Update helm charts

backend/strapi-sync/sync.js
=> CMS-781: Update sync script to use hasReservations from Strapi

frontend/src/router/pages/ParkDetails.jsx, frontend/src/router/pages/PreviewChanges.jsx, frontend/src/router/pages/PublishPage.jsx, frontend/src/router/pages/SubmitDates.jsx
CMS-773
Just update "season" references to "dates" or "year" in frontend pages.
=> CMS-773: Update season refereces to 'dates'

backend/middleware/adminJs.js, backend/migrations/20250313174503-add-editable-to-season.js, backend/models/season.js, backend/routes/api/parks.js, backend/routes/api/seasons.js, backend/strapi-sync/sync.js, frontend/src/components/ParkDetailsSeason.jsx, frontend/src/components/StatusBadge.jsx, frontend/src/components/StatusBadge.scss
=> CMS-772: Update old seasons statuses to be more accurate

frontend/src/router/pages/SubmitDates.jsx, frontend/src/router/pages/SubmitWinterFeesDates.jsx
=> CMS-746: Bug fix. Add null check to memoized property

frontend/src/router/pages/SubmitDates.jsx
CMS-756
One detail I missed in #166 - update `formSubmitted` when clicking the "Continue to preview" button so the validation will include the missing start/end dates.
Moved it to the submit functions instead of the save function.
=> CMS-756: Mark form submitted before validating

backend/routes/api/parks.js
CMS-8001
If a park only has statuses "on API" and "not provided", return "on API".
=> CMS-801: Fix bug for parks with 'not provided' status

frontend/src/styles/global.scss
CMS-772
Just the colour of disabled text buttons
=> CMS-772: Change text colour of disabled buttons

frontend/src/router/pages/ParkDetails.jsx
CMS-705
A small tweak to show the feature type name in lowercase when it's used in a sentence in the flash message
=> CMS-705: Show feature type name in lowercase on flash message

backend/migrations/20250319001529-add-admin-note-to-dates.js, backend/models/daterange.js, backend/strapi-sync/new-structure-migration.js, backend/strapi-sync/sync.js
CMS-753
This will simply send all the winter fee dates that we imported from Strapi's old collection to Strapi's new collection.
It also added the adminNote field to the date model because they wanted it to be migrated too.
=> CMS-753: Migrate winter fee dates to new structure

helm/crunchy-postgres/README.md, helm/crunchy-postgres/values-alpha-dev.yaml, helm/crunchy-postgres/values-alpha-test.yaml, helm/crunchy-postgres/values-dev.yaml, helm/crunchy-postgres/values-prod.yaml, helm/crunchy-postgres/values-test.yaml
CMS-000 (No ticket)
Increase volume sizes, and add S3 bucket details to TEST and PROD to store PG backups in a second repo.
This also keeps PROD and TEST the same (in terms of HA replicas and everything else)
=> CMS-000: Update volume sizes, add S3 backup repos

frontend/src/router/pages/PreviewWinterFeesChanges.jsx, frontend/src/router/pages/SubmitWinterFeesDates.jsx, frontend/src/router/pages/WinterFeesSeasonPage.jsx
CMS-625
I forgot to implement the scrolling logic on the Winter fee edit page in #185 so this is the exact same changes, but copied onto the Winter fee pages.
=> CMS-625: Add scroll anchor to winter edit page

frontend/package-lock.json, frontend/package.json, frontend/src/main.jsx, frontend/src/router/index.jsx
CMS-648
A small change to just suppress some console warnings about features that will change in React router v7, even though we're using v6... They were annoying and they didn't affect our app, but they started showing when we upgraded from a previous version.
This branch updates to the latest 6.x.x version, and adds feature flags to opt in to the new features and hide the console warnings. Everything should still work the same because we're not using the new features.
=> CMS-648: Update react router and add v7 flags

frontend/src/router/pages/PreviewChanges.jsx, frontend/src/router/pages/PreviewWinterFeesChanges.jsx
CMS-367
Correcting the button text on the "Preview" view for "doot-submitter" users to align with a Figma mockup Manuji found 👍
=> CMS-367: Update button text

frontend/src/components/TouchMenu.jsx, frontend/src/router/layouts/MainLayout.jsx
CMS-634
A bug fix and a style tweak from Manuji's QA notes on the touch nav menu in DOOT. 
Updated the displayed user name to be black so it's more consistent with how it looks on the "legacy-frontend" and fixed the inital state of the menu so it's not already open when you load the page.
=> CMS-634: Hide touch menu by default, update name color

backend/middleware/adminJs.js, backend/migrations/20250513000815-add-in-reservation-system-field-to-park.js, backend/migrations/20250513000843-add-in-reservation-system-field-to-feature.js, backend/models/feature.js, backend/models/park.js, backend/routes/api/parks.js, backend/strapi-sync/sync.js, frontend/src/components/FilterPanel.jsx, frontend/src/router/pages/EditAndReview.jsx
CMS-787
- BE: Import `inReservationSystem` from Strapi `park-operation` (park level) and the `park-operation-sub-area` (feature level) in Strapi
- Note: Except for the PROD environment, none of the entries has `inReservationSystem`
- If value is null in Strapi, it'll be false in DOOT
- BE: Add `inReservationSystem` column to Park and Feature table, and the API `/park` endpoint
- FE: Add a filter functionality
- Add the AdminJS meta title
=> CMS-787: Add inReservationSystem to filter parks and features

backend/models/feature.js, backend/models/park.js, backend/models/parkarea.js, backend/models/season.js, backend/routes/api/parks.js, frontend/src/components/EditAndReviewTable.jsx, frontend/src/router/pages/EditAndReview.jsx
CMS-894
- Get all of `parkArea` in `park`
- Get `feature` in `parkArea` if it has `parkAreaId`
- Get `feature` in `park` if it doesn't have `parkAreaId`
- Get `season` in `park`/`parkArea`/`feature` if its `publishableId` is matched
- Add `readyToPublish` from `season` to custom grouped dates to display a flag
- Code clean up
=> CMS-894: Update park API endpoint

frontend/src/router/pages/EditAndReview.jsx
CMS-987
- Fix filtering status
- Check `currentSeason` at each level 
- Fix filtering date types
- Check `season`, `dateRange`, `dateType` at each level
- Fix filtering feature types
- Check `featureType` at the ParkArea level and Feature level
=> CMS-987: Fix filtering status

backend/routes/api/seasons.js, frontend/src/components/FormPanel.jsx, frontend/src/components/SeasonForms/AreaSeasonForm.jsx, frontend/src/components/SeasonForms/FeatureSeasonForm.jsx, frontend/src/components/SeasonForms/ParkSeasonForm.jsx
CMS-872
- Update `isDateRangeAnnual` state when the save button is clicked
=> CMS-872: Save is date range annual update

frontend/src/components/DateRangeFields.jsx, frontend/src/components/GateForm.jsx, frontend/src/components/SeasonForms/AreaSeasonForm.jsx, frontend/src/components/TimeRangeForm.jsx
CMS-1043
- CMS-1043: Add default time for the gate time when the field is focused
- CMS-1033: Fix the spacing issue
- CMS-872: Fix the `DateRangeAnnual` checkbox id issue
=> CMS-1065: Add default time when it is focused

frontend/src/router/layouts/MainLayout.jsx, frontend/src/router/layouts/MainLayout.scss
CMS-905
- Add banner on test site (except for PROD env)
=> CMS-905: Add banner on test site

backend/routes/api/parks.js, frontend/src/components/FormPanel.jsx
CMS-1119
- Clear all gate-related data if it's been changed to `hasGate` False at Park/Area/Feature level
- It retains the data until the form is saved
- Hide operating dates from the table if a park has `hasGate` FALSE
=> CMS-1119: Remove operating dates from table if park has hasGate false

frontend/src/components/Unauthorized.jsx, frontend/src/router/AccessProvider.jsx, frontend/src/router/layouts/MainLayout.jsx
CMS-1089
Added an error message to the V2 app for users with no keycloak roles
Note: In order to test this locally with BCeID you will need to change your keycloak to test instead of dev. The Keycloak IDP on dev has the wrong secret key and it cannot log in.
=> CMS-1089: Add error page for login

frontend/src/components/FormPanel.jsx
CMS-1129
- Fix bcparks.ca typo
=> CMS-1129: Fix bcparks.ca typo

frontend-legacy/src/components/page/home/Home.js, frontend/src/hooks/useAccess.js, frontend/src/router/AccessProvider.jsx, frontend/src/router/ProtectedRoute.jsx, frontend/src/router/index.jsx, frontend/src/router/layouts/MainLayout.jsx, frontend/src/router/pages/LoginPage.jsx, frontend/src/router/pages/LoginPage.scss
CMS-960
Added BCeID login to the V2 app.  
Note:
1. The "Register for a BCeID link currently goes to the BCeID service directory entry for the A&R application
2. In order to test this locally with BCeID you will need to change your keycloak to test instead of dev. The Keycloak IDP on dev has the wrong secret key and it cannot log in.
=> CMS-960: Part 2 Add BCeID login to V2 app

frontend-legacy/src/components/page/error/Error.js, frontend/src/router/layouts/LandingPageTabs.jsx
CMS-960
Fix two issues reported by QA
=> CMS-960: Fix redirect and template flash issues on login pages

frontend/src/router/layouts/MainLayout.jsx
CMS-1089
Fix a javascript error that broke alpha-dev
=> CMS-1089: Fix broken build

frontend-legacy/src/components/page/error/Error.js, frontend/src/components/Unauthorized.jsx
CMS-1089
Updated the messages for unauthorized users to match the screenshot in the ticket
=> CMS-1089: Update unauthorized message

frontend/src/router/AccessProvider.jsx
CMS-1151
This fixes an issue with BCeID logout not working
=> CMS-1151: Fix bceid logout

backend/tasks/populate-previous-dates/populate-previous-dates.js
CMS-904
- Additional change on https://github.com/bcgov/bcparks-staff-portal/pull/276
- These dates from the Excel file are past dates, so they were already approved, but haven't been published yet to Strapi.
=> CMS-904: Update populate previous date script

backend/routes/api/filter-options.js, backend/routes/api/parks.js, backend/strapi-sync/sync.js, backend/tasks/create-date-types/README.md, backend/tasks/create-date-types/create-date-types.js, backend/tasks/create-date-types/date-types.js, frontend/src/components/GateForm.jsx, frontend/src/components/SeasonForms/ParkSeasonForm.jsx
CMS-1156
- Update the filter display "Operating" to "Gate"
- Update the table display "Operating" to "Gate"
- Split a file `create-daye-types.js` from `sync.js` for future update
- Update the gate form wording, tooltip, and title
- To update the "Gate date" tooltip text, run `node tasks/create-date-types/create-date-types.js`
=>  CMS-1156: Update gate form wording

frontend-legacy/entrypoint.sh, frontend-legacy/src/components/composite/header/Header.css, frontend-legacy/src/components/composite/header/Header.js, frontend-legacy/src/components/composite/responsiveDrawer/responsiveDrawer.js, frontend-legacy/src/components/page/appDashboard/AppDashboard.js, frontend/Caddyfile, frontend/Dockerfile.prod, frontend/src/config/keycloak.js, frontend/src/router/index.jsx, frontend/vite.config.js, helm/deployment/templates/frontend/frontend-deployment.yaml
CMS-1083
This PR changes the DOOT URL from /v2 to /dates.
It also removes "V2" from the header and adds the red "Testing environment only banner" to the legacy app so it matches the V2 app.  
Note: When this is merged, there may be some post deployment tasks that need to be completed in OpenShift 
Specifically 
- The VITE_OIDC_LOGIN_REDIRECT will need to be updated
- A post deployment tasks ticket will need to be created to document all the steps required to get the app working
=> CMS-1083: Update DOOT URL

frontend-legacy/src/components/composite/responsiveDrawer/responsiveDrawer.js, frontend-legacy/src/components/page/appDashboard/AppDashboard.js, frontend/src/components/NavSidebar.jsx, frontend/src/components/TouchMenu.jsx, frontend/src/components/shared/navItems.js, frontend/src/config/permissions.js, frontend/src/hooks/useAccess.js
CMS-874
With this change, users will only see menu nav items corresponding to their assigned keycloak roles.
=> CMS-874: Show/hide nav menu items depending on user permissions

backend/tasks/populate-park-tier-types/2025-tier-data.json
CMS-1132
- Add missing data for Bear Creek Park so that it can have the correct `hasTier1Dates` value
- For testing: run `node tasks/populate-park-tier-types/populate-park-tier-types.js`
- Or you can go to AdminJS > Park > Bear Creek Park and change it manually
=> CMS-1132: Update 2025 tier data

backend/routes/api/seasons.js, backend/utils/firstComeFirstServedHelper.js
CMS-957
- When an approver approves the Operating dates and the Reservation dates for "Frontcountry campground" or "Walk-in camping", the FCFS dates are calculated and added to DateRanges automatically
=> CMS-957: Update first come first served function

backend/tasks/create-seasons.js
CMS-1194
The create-seasons script creates seasons and blank dates for **Group campground** features for the _year after the operatingYear_. This branch updates the script to do the same thing for **Picnic shelter** features. Unfortunately it does not refactor or move the file but I will make sure there's something in the backlog to give it some attention.
To test, `node tasks/create-seasons.js 2026` and note the output at the bottom. It should have a block like this:
> Creating blank DateRanges for 2027
Found 65 Seasons for 2027
136 applicable DateRanges. Checking if any exist already...
104 applicable DateRanges already exist.
Creating 32 missing DateRanges
Created 32 blank DateRanges for 2027
If you run it a second time, it should say there's noting to create:
> 136 applicable …
=> CMS-1194: Include Picnic Shelters in Group Camping "next year" logic

frontend/src/router/layouts/LandingPageTabs.jsx
CMS-981
- Update role check with `hasAnyAccess` for the export page
=> CMS-981: Update role check for export page

backend/routes/api/export.js
CMS-1250
- If the gate opens/closes at a specific time, show that time
- If the gate opens/closes at dawn/dusk, show "Opens at dawn" or "Closes at dusk"
=> CMS-1250: Add gateOpensAtDawn and gateClosesAtDusk to export file

frontend/src/components/NoParkAccess.jsx
CMS-1261
Changed the message to wording suggested by BC Parks.
=> CMS-1261: Change message text

frontend-legacy/src/components/page/home/Home.js
CMS-1261
Handle redirection to DOOT from the home page too, not jst the error page.
=> CMS-1261: Handle alternate redirection to DOOT
